### ISSUE TITLE
new operator tests cause build failed

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#1000]
@rbouckaert the build failed in my merge commit is very weird. According to the error message: 

```
[javac] /src/test/beast/evolution/operator/BactrianDeltaExchangeOperatorTest.java:6: error: package org.apache.commons.math3.stat does not exist
[javac] import org.apache.commons.math3.stat.StatUtils;
[javac]                                     ^
[javac] /src/test/beast/evolution/operator/BactrianRandomWalkOperatorTest.java:5: error: package org.apache.commons.math3.stat does not exist
[javac] import org.apache.commons.math3.stat.StatUtils;
[javac]                                     ^
...
```

The build cannot find `org.apache.commons.math3.stat.StatUtils`. I looked at the [test build](https://github.com/CompEvol/beast2/blob/7fd4f3fda114f097e1850929b57882a14d71d6ae/build-testing.xml#L19), the apache math was not in the dependency list. The new operators tests in #834 committed about 1 week ago require `org.apache.commons.math3.stat.StatUtils`, but it was not added into the dependencies. 

So I am so innocent. But it is concerned that the test build should fail when those commits checked in about a week ago.

**Comment by walterxie** [comment]
celebrate 1000th issues

**Comment by walterxie** [comment]
```
BUILD FAILED
34
/build-testing.xml:71: Directory does not exist: /build/beast/core/util
```
test build seems very broken ...

**Comment by walterxie** [comment]
Hi @rbouckaert, the tests are broken because of your recent change of core Java packages, such as `beast.core` => `beast.base`. I changed the line https://github.com/CompEvol/beast2/blob/59fd1673b6f2fd24a29109199a498b6f63872f44/build-testing.xml#L72 to `<fileset dir="${build}/beast/base/" includes="Log*.class" />`, but most of tests were still failed. So I have to comment it out. Then it seems fixing most of tests, expect of some looking for the files.

**Comment by rbouckaert** [comment]
At a25fcc1a8bf95de45c05c7d8ff9f7ba068b11e26 the tests passed, so there was nothing wrong with the test build system before the merge that followed.

Reverting the merge of 7fd4f3fda114f097e1850929b57882a14d71d6ae that caused da5e2639d06d944b912f4aa189f54f755d4ec4fb and e85fcd4f006e605808ebf7f5a98dba5b76d6cb3b to reappear (which were not there before the merge, otherwise tests for a25fcc1a8bf95de45c05c7d8ff9f7ba068b11e26 would not have passed) will probably fix the thing. 

Revering the head back 5 steps to 083fb8bc062f74fe3c39243bc2742beeed67c27d, then reapply a25fcc1a8bf95de45c05c7d8ff9f7ba068b11e26 is the easiest way I can think of getting there.

**Comment by walterxie** [comment]
Many thanks for the advice. I will try after lunch. We may need to create a tag, after the master branch is back to normal.

**Comment by walterxie** [comment]
The build is finally fixed https://github.com/CompEvol/beast2/commit/518a0ed4178425251690365bd1379afd46719c17. Hi Remco, please confirm everything that you required is in this commit, so I can close this issue. 
I suggest to create a tag.
