### ISSUE TITLE
CladeAge in BEAST 2 v2.7.0

### ISSUE THREAD

**Issue by JamesHowie14** [CompEvol/beast2#1051]
Hi - I hope not too stupid. But, I installed BEAST2 v 2.7.0. I noticed that if I click BEAUTi > File > Manage Packages, to get into the Package Manager, I now don't have the option for CladeAge, for instance.

I tried to add the URL "https://github.com/CompEvol/CBAN/blob/master/packages2.6.xml" in the Package repositories. 
But this did not work. 

Is there any way to get such packages in BEAST 2 v 2.7, or do I need to use v2.6 or lower to access these?

Thanks so much for any help.

**Comment by rbouckaert** [comment]
@JamesHowie14 the CladeAge package and quite a few other packages have not been migrated to v2.7 yet. Though I made a start to it, due to the change in the GUI, there is quite a bit of work involved in migrating CladeAge.

You can run v2.6 and v2.7 next to each other -- they use different package directories -- so if you need packages that have not been migrated yet you should use v2.6.

**Comment by JamesHowie14** [comment]
HI @rbouckaert, OK brilliant, thanks for that - makes sense. I'll go ahead with both versions. Thanks!
