### ISSUE TITLE
BEAUTi 2 fails to launch apps

### ISSUE THREAD

**Issue by ml0094** [CompEvol/beast2#1061]
Hello,
Quite simply using the BEAUTi 2 GUI, I seem unable to launch apps. Navigating to launch apps, I do see all the installed apps and packages, but clicking on the launch app button fails to do anything. I am running Windows 11 x 64 bit.  Java version 8 update 333. The issue was observed with OBAMA and MODEL_SELECTION. The issue does not extend to all applications. For example, the methods file analyzer and the methods generator both seem to be working.

**Comment by rbouckaert** [comment]
@ml0094 thanks for the bug report -- which BEAST version are you using?

In v2.7.2, it looks like `Application.launch()` is called multiple times: once for BEAUti, and once for the app to be launched causing an exception: `java.lang.IllegalStateException: Application launch must not be called more than once`.

A workaround for now is to launch apps via the AppLauncher application that comes with BEAST instead of launching them via BEAUti.

**Comment by ml0094** [comment]
Looks like my version is v2.7.1

**Comment by rbouckaert** [comment]
Should be fixed for `beastfx.app.tools.Applications` based apps by by https://github.com/CompEvol/BeastFX/commit/2ba94d36ab8412df65637d7a0b46cd26a7de48c6
