### ISSUE TITLE
Generalise Node.getLength() implementation

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#1085]
The `getLength()` method in `Node` is final (not quite sure why), so cannot be overwritten. 
Its implementation uses `getParent().height - height` to calculate the length.
Replacing this by `getParent().getHeight() - getHeight()` would allow classes derived from `Node` (like `BinaryNode` in the starbeast3 package) to implement its own heights on nodes.

**Comment by alexeid** [comment]
Why would length ever be defined differently than this?

From: Remco Bouckaert ***@***.***>
Date: Wednesday, 15 February 2023 at 10:52 AM
To: CompEvol/beast2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CompEvol/beast2] Generalise Node.getLength() implementation (Issue #1085)

The getLength() method in Node is final (not quite sure why), so cannot be overwritten.
Its implementation uses getParent().height - height to calculate the length.
Replacing this by getParent().getHeight() - getHeight() would allow classes derived from Node (like BinaryNode in the starbeast3 package) to implement its own heights on nodes.

**Comment by rbouckaert** [comment]
The height is not necessarily stored in the height member of `Node`: in the `BinaryNode` it is stored in the tree, which contains an array of heights. It is not a matter of definition but implementation.

**Comment by alexeid** [comment]
Ah, just changing to getHeight() rather than .height. Makes total sense.


From: Remco Bouckaert ***@***.***>
Date: Wednesday, 15 February 2023 at 11:08 AM
To: CompEvol/beast2 ***@***.***>
Cc: Alexei Drummond ***@***.***>, Comment ***@***.***>
Subject: Re: [CompEvol/beast2] Generalise Node.getLength() implementation (Issue #1085)

The height is not necessarily stored in the height member of Node: in the BinaryNode it is stored in the tree, which contains an array of heights. It is not a matter of definition but implementation.
