### ISSUE TITLE
Class (orc.consoperators.UcldScalerOperator) could not be found

### ISSUE THREAD

**Issue by Chonghao98** [CompEvol/beast2#1157]
Hi,

I got the following error when I used BEAST2.

"""
Random number seed: 1719928016096

File: Alphainfluenzavirus_influenzae.xml seed: 1719928016096 threads: 25
Loading package BEAST.base v2.7.7 BEAST.app v2.7.7 BEASTLabs v2.0.2 ORC v1.2.0    

Error 1017 parsing the xml input file

Class could not be found. Did you mean beast.base.evolution.operator.ScaleOperator?
Perhaps a package required for this class is not installed?

Error detected about here:
  <beast>
      <run id='mcmc' spec='MCMC'>
          <operator id='ORCAdaptableOperatorSampler_sigma.c:Alphainfluenzavirus_influenzae' spec='AdaptableOperatorSampler'>
              <operator id='ORCucldStdevScaler.c:Alphainfluenzavirus_influenzae' spec='orc.consoperators.UcldScalerOperator'>
"""
I manually installed ORC (version 1.2.0) in ~/.beast/2.7/ (i.e. in ~/.beast/2.7/ORC directory). Can anyone help me to solve this problem?

Thank you.

**Comment by rbouckaert** [comment]
Perhaps something went wrong with the package installation: can you check that the file `~/.beast/2.7/ORC/lib/ORC.addon.jar` and `~/.beast/2.7/ORC/version.xml` exist and no other files are in `~/.beast/2.7/ORC/lib`? 

By the way, is there a reason not to use the packagemanager: `/path/to/beast/bin/packagemanager -add ORC` (where `/path/to` the path to where BEAST is installed) instead? It should be more robust, since it installs dependent packages as well, but I am curious to what reason there is for this not to be feasible.

**Comment by Chonghao98** [comment]
Thanks for your help. It turns out to be the installation problem. I found that I encoutered an error with 'ant install' in ORC dir, and the error suggests that the build.xml in ORC dir needs another build.xml in ~/.beast/2.7/beast2/, but I do not have ~/.beast/2.7/beast2 dir.
For the use of packagemanager, I encoutered the following error
"""
Access URL : https://raw.githubusercontent.com/CompEvol/CBAN/master/packages2.7.xml
Getting list of packages ...Error reading the following package repository URLs: https://bitbucket.org/rrb/cbanclone/raw/master/packages2.7.xml
Could not get an internet connection. The BEAST Package Manager needs internet access in order to list available packages and download them for installation. Possibly, some software (like security software, or a firewall) blocks the BEAST Package Manager.  If so, you need to reconfigure such software to allow access.
"""
I can successfully download 'https://raw.githubusercontent.com/CompEvol/CBAN/master/packages2.7.xml' by using wget, so this is not an internet issue. I do not know how to solve this problem, so I tried mannully installation.

**Comment by rbouckaert** [comment]
Perhaps there is some security software blocking internet access from programs downloaded from internet. Anyway, the best way to install a package by hand is to create a directory `~/.beast/2.7/ORC`, change to that directory, get the ORC package (`wget https://github.com/jordandouglas/ORC/releases/download/v1.2.0/ORC.addon.v1.2.0.zip` for the current version) and unzip the file (`unzip ORC.addon.v1.2.0.zip`).

Since ORC depends on BEASTLabs, installing BEASTLabs (`wget https://github.com/BEAST2-Dev/BEASTLabs/releases/download/v2.0.0/BEASTlabs.package.v2.0.2.zip` for the current version) is required too.

Hope this helps.

**Comment by Chonghao98** [comment]
The two files you provided worked. Thank you very much.
