### ISSUE TITLE
BEAUti FASTA import incorrectly reads Nucleotides as Amino Acids

### ISSUE THREAD

**Issue by alexeid** [CompEvol/beast2#180]
There are many packages that get this guesswork right. JEBL is an obvious one to use.

From Nicola Lewis in BEAST user forum:

a) input fasta nucleotide alignment was read as amino acids - therefore couldn't access appropriate models. I checked there weren't any non-standard nucleotide values, and also tried replacing '- ' 'with ? - to no avail. I fixed by converting the fasta to a nex.

**Comment by aersoares81** [comment]
Same with me! I had to convert to nexus so BEAUTI would import the alignment as nucleotides.
I thought the "N" sites on the alignment threw it off, but I replaced them with gaps and it didn't fix it.

**Comment by rbouckaert** [comment]
Quick fix: let the user choose at time of importing the fasta file through a dialog if the type is not defined through the file extension. One of the choices should be that all following alignments are of the same type so that when many alignments are imported at the same time the dialog does not need to be clicked on every time.
