### ISSUE TITLE
flat line persisting during sampling

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#244]
Subject: Re: flat line persisting during sampling
Reply-To: beast-users@googlegroups.com

I've attached my xml file as well.

On Thursday, November 20, 2014 8:06:34 AM UTC-5, jssd...@gmail.com wrote:
I'm running a random local clock analysis in BEAST2, and have been getting a mysterious flat-line behavior during sampling. At different points early in the analysis, the traces for all the parameters flat-line for several hundred thousand generations, and then occasionally move before flat-lining again. The earliest stages of the run look fine in the trace.

Is this something going on with the operators? I've attached an example image.

~John

XML is attached in the email

**Comment by rbouckaert** [comment]
From a related case I think what probably happens is that the meanClockRate parameters are becoming very large, and then due to numeric instability chains will get stuck with large positive likelihoods.

To prevent this from happening, you can set the upper bound on the
meanClockRate. In the xml, add an upper attribute to each of the meanClockRate
parameters, so
        <parameter id="meanClockRate.c:p1pos" name="stateNode">1.0</parameter>
becomes
        <parameter id="meanClockRate.c:p1pos" name="stateNode"
upper="2.0">1.0</parameter>
assuming 2.0 is a reasonably large upper bound for your data.
