### ISSUE TITLE
BEAUti guess trait "read from file" does not pick up 1st mapping 

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#247]
Use "read from file" to load traits, such as dates, but the 1st line of mapping seems not to be loaded, the date is set to 0.

**Comment by rbouckaert** [comment]
I suppose if the first word on the first line matches a taxon name, then in al likelihood it is OK to interpret it as a data line instead of a header -- even though the documentation says it otherwise. Parsing is already a bit loose: it does not fail if there are extra data lines not matching any taxa, and vice versa, but just produces appropriate warnings on STDERR.

**Comment by alexeid** [comment]
STDERR is not generally accessible to users of BEAUti and BEAST. If we are going to put important stuff on STDERR then we have to reveal that stream of messages to the user somehow...

**Comment by rbouckaert** [comment]
STDOUT and STDERR can be seen under the Help/Messages menu in BEAUti when started with the -capture argument.
