### ISSUE TITLE
Numerical Instability on Resume

### ISSUE THREAD

**Issue by armanbilge** [CompEvol/beast2#329]
Minor numerical differences when reloading a state file can prevent an analysis from resuming due to an `Start likelihood: -Infinity` error (I observed this in an EBSP analysis). @rbouckaert suspects that loss of precision when reading/writing trees causes this problem.

**Comment by rbouckaert** [comment]
This happens in Coalescent.calculateLogLikelihood, in this line
            if (intervalArea == 0 && duration != 0)
'intervalArea' became 0, but 'duration' become less than 1e-10, but not zero. The second comparison should be 'duration > EPSILON' where EPSILON = 1e-10 seems a good value since it can deal with numeric instability on resume in this example.

**Comment by armanbilge** [comment]
Unfortunately this is still a big problem for me, even when I make EPSILON as little as Double.MIN_VALUE. I cannot resume jobs using an exponential growth coalescent model.

**Comment by rbouckaert** [comment]
Did you run this in a debugger and did it trace back to the same bit of code? 
Making epsilon larger (or relative to magnitudes) instead of smaller may help.

**Comment by rbouckaert** [comment]
On the user list, reporting running into this:
https://markmail.org/message/ffz6da7f6adova4h?q=beast-users+date:201803+from:%22Koenievdl%22&page=1
