### ISSUE TITLE
Turning a double[] into a beast.core.Function

### ISSUE THREAD

**Issue by Anaphory** [CompEvol/beast2#330]
Is there a way to cast a `double[]` value into something that implements `beast.core.Function`? It does not look difficult to write such a class, but before I start doing so I want to know whether I am overlooking something.

The intended use case is for tests. In particular, I want to write a test case for a correlated substitution model, in order to make sure that my index arithmetic is correct. Just as `GeneralSubstitutionModel`, my class has an `Input<Function> ratesInput`, which I want to specify in a test, to compare the resulting `double[][] getRateMatrix` with what I would expect. (I know that value is `protected`, is there any way to obtain protected values in a test, or do I need to check the transition rates derived from it? I have no experience actually writing tests like that in Java.)

**Comment by rbouckaert** [comment]
If you use Double instead of double, you can use RealParameter, since it implements Funcion. To create a RealParameter using the Double[] constructor, e.g. like so:

Double [] rates  = new Double {}[1.0, 2.0,3.0,4.0,5.0,6.0};
RealParamter ratesParam = new RealParamter(rates);

Then use it to initialise the subst. model:

GeneralSubstitutionModel s = new GeneralSubstitutionModel();
s.initByName("rates", ratesParam, ...);
