### ISSUE TITLE
hyperparameters not estimated in discrete trait analysis

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#335]
When I set up a discrete trait analysis BEAUti defaults to Gamma priors on the relativeGeoRates and traitClockRate parameters.  The "estimate" checkboxes for the alpha and beta parameters in each case are set by default to true.  However, there are no operators corresponding to these hyperparameters shown in the list of operators in the Operators panel, and none are produced in the resulting XML.  Unchecking and rechecking the "estimate" checkboxes is enough to produce the required operators.

**Comment by rbouckaert** [comment]
This is probably the result of using values for the Gamma parameters specified through strings (alpha="1.0" instead of the considerable longer <alpha spec='parameter.RealParameter' estimate='false' value='1.0'/>). I fixed the template for this in beast-classic. Let me know if this does not fix the problem.

Perhaps the default for estimate on StateNodes should be false.

**Comment by tgvaughan** [comment]
Thanks Remco, this does seem to fix the problem.  You should also modify the prior for traitClockRate in a similar way as it has the same problem.

**Comment by rbouckaert** [comment]
Fixed in beast-classic.
