### ISSUE TITLE
Need way to extract one or more elements from Functions.

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#360]
It would be great to have a Function that represents one or more element from an existing Function, analogous to the array slice operation implemented in many numerical programming environments.  This would provide a general way for assigning different priors to different components of a parameter, say.

**Comment by rbouckaert** [comment]
Why should this be in the core, and not in BEASTLabs?

**Comment by alexeid** [comment]
Because it is core.

**Comment by alexeid** [comment]
BEASTLabs already has core stuff in it like model comparison and MCMCMC, so it always needs to be installed anyway. So it's an ill-defined package because it's not a single model or class of models that is genuinely of interest to only a small subset of users.

**Comment by tgvaughan** [comment]
It's in the same (java) package as Sum.  If Sum is in the core, why shouldn't other Function operations?

**Comment by rbouckaert** [comment]
Is there an example where MCMCMC produces better ESS per computer cycle than plain old MCMC?

Model comparison is not in BEASTLabs, it is in the model-selection package.

**Comment by rbouckaert** [comment]
The core should be as small as possible, but sufficiently functional to do basic analyses that made BEAST 1 famous: divergence dating, tip sampling, *BEAST. This is in order to make learning the core as easy as possible.

If you look at package dependencies, this has been a successful strategy so far: almost all packages depend on the core only, with BEAST-CLASSIC depending on BEASTLabs as one of the exceptions.

If anything I would like to reduce the core instead of augmenting it. For example *BEAST can benefit a lot from the STACEY operators, so perhaps all *BEAST stuff should be in its own multi-species coalescent package.

BEASTLabs contains everything in the category "It would be great to have" just like this issue starts and that is of general interest.

Sum is used in the EBSP template, and therefore required to be in the core. Slice is not required by anything in the core, hence should not be in beast2, but in another package.

**Comment by tgvaughan** [comment]
I totally agree that *BEAST should be in its own package, along with EBSP.  Surely low-level stuff like array manipulation is closer to what should be in the core?

**Comment by tgvaughan** [comment]
The alternative would be to add slicing capability to the Function interface itself.

**Comment by alexeid** [comment]
Tim made the point I was trying to make: models should be in packages, machinery should be in the core.

**Comment by rbouckaert** [comment]
Does anyone have an example file where MC3 outperforms MCMC?

**Comment by rbouckaert** [comment]
I agree functional stuff should be in the core but only after it has proven its usefulness.

Having it around in BEASTLabs for a  while allows to proves its usefulness; if packages are using it, it should be moved to the core, otherwise it can stay in BEASTLabs. Experiments definitely should not be introduced in the core unless absolutely required by other parts of the core.

**Comment by alexeid** [comment]
In terms of the size of the credible set of trees I have always seen MC3 outperform MCMC. In my experience MC3 produces a larger credible set of trees (and therefore slightly lower posterior probabilities on most clades) which I have taken to be a sign of more efficient and more accurate sampling of the posterior. There is a set of tests from about 7 years ago on the beast1 website but not sure if they survived the migration to the Drupal.

**Comment by tgvaughan** [comment]
It seems beast.core.util.Slice was removed just before 2.3.0 was released.  Was this an accident or an executive decision? ;-)

**Comment by rbouckaert** [comment]
It is in BEASTLabs now to see whether it gets much traction. If it turns out to be useful for many packages it should go in the core, but not before this has been proven.

**Comment by tgvaughan** [comment]
This would immediately replace some other junk that's in BEASTLabs btw, like ExcludablePrior.  If we extended Function to permit setting values, it could also remove necessity of hacks such as setting the degrees of freedom for scale operators.

**Comment by rbouckaert** [comment]
But Slice only allows a range (from start index, to start index + count), while ExcludablePrior allows any subset of entries.

**Comment by tgvaughan** [comment]
That can easily be changed!

**Comment by rbouckaert** [comment]
Sure, but Slice wouldn't be Slice any more  :-)

**Comment by tgvaughan** [comment]
True, we need general element extraction as well.  Basically we need a class that implements R's [] operator.
