### ISSUE TITLE
RandomClock clock rates

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#383]
Clock rates in random local clock can become very large (>10^19) which leads to numeric issues.

Perhaps putting an upper bound in the BEAUti template at say 1000 would prevent this.

**Comment by alexeid** [comment]
What is the default prior? Since the rates can be sampled outside the likelihood when the corresponding indicator is zero they must have a compact and proper prior or the posterior is meaningless. A uniform from 0 to 1000 is not compact.

**Comment by rbouckaert** [comment]
Hmm, there appears to be no prior on rates in the BEAUti template. 
Perhaps a Gamma(0.5, 2.0) prior makes more sense.

**Comment by alexeid** [comment]
That would be okay if they are relative rates but potentially catastrophic if the are absolute rates. Depends on the rest of the set up I guess... 

We should try to match the BEAST1 parameterization and priors because I remember that we had to work quite hard to get something that worked out of the box without much fiddling.
