### ISSUE TITLE
Production BEAUti does not report errors.

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#388]
I'm talking about actual errors here, not debug output.  I have a template that works under the development version of beauti but not the latest release, but no additional information.  All I know is what I can see - beauti fails to load an alignment.  No output at all is written to stdout/stderr and no message is displayed.

**Comment by rbouckaert** [comment]
Stdout and stderr are written to a stream that you can see by checking the Help/Messages menu. This is in order for users to be able to report problems when BEAUti is started from double clicking its icon.

**Comment by tgvaughan** [comment]
Maybe actual errors should show some kind of warning though?  At the moment beauti just fails silently.

**Comment by alexeid** [comment]
Can’t it also be written to the stdout/stderr?

**Comment by alexeid** [comment]
Exceptions should alert user with a dialog box. But that is actually quite hard to fix because we have Exception throwing and catching designed into core methods, so that even RuntimeExceptions get prematurely caught and don’t filter up to the GUI. That is why methods should not declare that they throw a top level Exception, because it is two tempting for calling methods to catch it rather than propagate the throw Exception to every single method signature in the core. If we are going to make any radical changes that break backwards compatibility it should be to remove throw Exception from all core methods and actually throw whichever relevant (non RuntimeException) exception that should be thrown for each method.

**Comment by rbouckaert** [comment]
Writing to stoud/stderr as well as to a message stream is difficult, since System.out and System.err are redirected (using System.setOut, System.setErr). This is necessary to capture all output, since not everywhere in the code beast.core.util.Log is used, but System.err and System.out as well. Once you start redirecting stdoud and stderr, any output to it will end up in the handler.

What would be possible is to write to the message stream as well as a file stream, say beauti.log. The directory to write to could be $(user.dir), which could clutter the file system, or /tmp/ for mac & linux and c:\tmp\ or c:\temp\ for windows.

**Comment by alexeid** [comment]
So how about storing the original system out before setting the new one and then setting the new one with a CopyOutputStream (defined below) which is constructed with the original stdout stream and the second one that the app uses to display to user?

class CopyOutputStream extends OutputStream {
    private final OutputStream str1;
    private final OutputStream str2;

    public CopyOutputStream(OutputStream str1, OutputStream str2) {
        this.str1 = str1;
        this.str2 = str2;
    }

    @Override
    public void write(int b) throws IOException {
        str1.write(b);
        str2.write(b);
    }

    // ...

    @Override
    public void close() throws IOException {
        try {
            str1.close();
        } finally {
            str2.close();
        }
    }
}

**Comment by rbouckaert** [comment]
Ah yes, that works.

**Comment by rbouckaert** [comment]
Tim, does 32cab11 solve your problem?

**Comment by tgvaughan** [comment]
Yes, I think it does.  Thanks!

Also:

    ... not everywhere in the code beast.core.util.Log is used ...

I've never heard of this class!!  I'll definitely use it in future!
