### ISSUE TITLE
Suggestion to add tutorial

### ISSUE THREAD

**Issue by richelbilderbeek** [CompEvol/beast2#397]
I made a tutorial how to create a new tree prior [here](https://github.com/richelbilderbeek/Java/blob/master/Beast2TutorialCreateNewTreePrior/CreateNewTreePrior.md). 

I'd be happy to help put it somewhere closer to the BEAST2 documents. Or someone of you just copy it. Or receive some feedback on it.

If you do not think this is useful, that is fine as well and I'll accept this Issue being closed.

**Comment by rbouckaert** [comment]
Thanks a lot! 

I added a link from the tutorials page of the beast.org site.

Would you mind if I made a copy and put it in a https://github.com/BEAST2-Dev/beast2-docs?

**Comment by richelbilderbeek** [comment]
No, please feel free to use it!

**Comment by rbouckaert** [comment]
Cool! I copied the files and pointed the tutorials link to it. 

I  sent you an invite for BEAST2-Dev in case you want to update the tutorial.

**Comment by tgvaughan** [comment]
Hi @richelbilderbeek , nice tutorial - thanks for putting it together!  Just one minor point: you've placed the MyTreePrior class in the beast.evolution.speciation package.  This is not generally a good idea because all jars loaded by beast share the same namespace.  If somebody else writes a package containing beast.evolution.speciation.MyTreePrior there'll be a collision and one of the jars (either yours or theirs) won't be loaded.  I'd therefore be inclined to modify the tutorial to direct users to create their own package hierarchy and place new classes in these packages whenever possible.

**Comment by richelbilderbeek** [comment]
Hi @tgvaughan , please do improve the tutorial in the way your suggested. I wrote it especially to get such feedback. If the text and pictures will mismatch, I will do the grunt work and update the pictures.
