### ISSUE TITLE
TreeParser doesn't strip quotes from string metadata.

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#405]
For instance, `[&type="1"]` will result in a metadata entry with key `type` and value `"1"`.

**Comment by rbouckaert** [comment]
Perhaps it make sense to strip single and double quotes from labels as well, so for example

('First taxon':1.0,"O'Raillie's":1.0):1.0

has as taxa

First taxon
O'Raillie's

That way they are easier to match to taxa in alignments, if they are unquoted, since NexuParser strips quotes from taxon names.
If stripped, they may need to be put back in when writing out trees in NEXUS format.

**Comment by tgvaughan** [comment]
Is it legal to have quoted strings as labels?
