### ISSUE TITLE
how to plot the Birth-Death Skyline Serial results?

### ISSUE THREAD

**Issue by HK3008** [CompEvol/beast2#475]
I have finished the analysing for HCV sequences using “Birth-Death skyline serial” by BEAST2. according to the manual"Birth-Death skyline (BDSKY) turorial", we can plot the results use the R script bdsky_plot_2.1.1.R, but i could not find "bdsky_plot_2.1.1.R". Please give me some guide and help, Thanks!

**Comment by denisekuehnert** [comment]
Hi, the script is in the doc folder on github: 
https://github.com/BEAST2-Dev/bdsky/blob/master/doc/BDSKY_plot_2.1.1.zip

**Comment by alexeid** [comment]
Is this really closed? Shouldn’t we update the tutorial to avoid the question recurring?

**Comment by rbouckaert** [comment]
Perhaps, but if so it should be an issue for the BDSKY repository, not for this one.

**Comment by alexeid** [comment]
So user raised the issue in the wrong repository? Who is responsible for raising it in the right repository?

**Comment by tgvaughan** [comment]
I'd say the user, although I think there's understandable confusion here due to the fact that the beast2.org directly advertises package tutorials (such as the BDSky tutorial), giving the impression that they're part of the core.  If users interested in BDSky were instead quickly shuttled to the BDSky web page, I think they'd be less likely to make this mistake.
