### ISSUE TITLE
BEAUti crash - CUDA error: "Driver not initialized" from file <GPUInterfaceCUDA.cpp>, line 169.

### ISSUE THREAD

**Issue by alexeid** [CompEvol/beast2#500]
User opens BEAUti 2.3.3 and tries to load a file to run SNAPP. Crashes. When running from command line the following error message is obtained:

CUDA error: "Driver not initialized" from file <GPUInterfaceCUDA.cpp>, line 169.

It seems that CUDA is installed but not with a GPU driver. We should try to fail elegantly here. Can we check for the GPU installation before we call the function that produces this CUDA error?

**Comment by rbouckaert** [comment]
I think this is due to having CUDA installed, while there is no CUDA device available -- installing CUDA is default when clicking all the default settings in the BEAGLE installation program, so this is an easy mistake to make.

The BEAGLE library will be automatically loaded when a TreeLikelihood is created, so in case of a failure, the TreeLikelihood should be prevented from doing that.

If I am not mistaken, the crash is caused by the BEAGLE library halting the process. So, to test for this, first create a second process that tests for this problem, and if that process fails warn the user appropriately.

**Comment by alexeid** [comment]
I know why it is caused, but it is still a bug that BEAUti doesn’t fail more elegantly.

**Comment by rbouckaert** [comment]
So, to test for this, first create a second process that tests for this problem, and if that process fails warn the user appropriately.

**Comment by rbouckaert** [comment]
To check CUDA is installed:

/System/Library/Extensions/CUDA.* 
/Library/Frameworks/CUDA.framework 
/Library/LaunchAgents/com.nvidia.CUDASoftwareUpdate.plist 
/Library/PreferencePanes/CUDA/Preferences.prefPane 
/System/Library/StartupItems/CUDA/ 
/Developer/NVIDIA/CUDA-* 
/usr/local/cuda

All of these should not exist on OSX without CUDA capable hardware. An alternative solution is to check for these files on OSX, and only try the sanity check then, so other OSs and instances do not need this check. Perhaps a way to suppress this check might be good too.
