### ISSUE TITLE
XML should store a list of needed packages.

### ISSUE THREAD

**Issue by SimonGreenhill** [CompEvol/beast2#558]
As the BEAST2 package system proliferates, there are more and more packages that add functionality. 

One side effect of this is that it becomes harder to distribute XML files as it's not clear what packages they rely on. This goes against the philosophy of having the XML file contain everything needed to replicate the analysis. And it can lead to puzzling errors e.g. one I came across recently was:

```
nullClass could not be found. Did you mean beast.evolution.tree.RandomTree?
```

This was because I didn't have (I think) the BeastLabs package installed. 

It would be nice to add the information that an analysis requires package X (version Y) into the XML file somehow.

One alternative would be to generate a more understandable error message e.g. "...which can be found in Package X", but I'm not sure how this might work as BEAST doesn't know about all the add-ons that are out there until they're installed.

However, BEAUTi knows what packages its using to generate the XML, so another alternative would be to add a list of required packages into the XML when generated as an explicit "requires" style statement. This could also include version information e.g. 

```
<requires package="BeastLabs" source="http://...." version="..." />
```

Or perhaps by injecting it into the <beast> namespace tag:

```
<beast beautitemplate='..' beautistatus='' namespace="beast.core:2.4.1:beastLabs:1.5.3...">
```

... and BEAST could check this when running and fail if it can't find the required package (and same/newer version).

**Comment by rbouckaert** [comment]
Hi Simon,
We are aware of the problem (see #91), but unfortunately, it is not trivial to detect which packages are used by an analysis. We are still thinking about a good solution, but will think a bit harder --  thanks to your encouragement.
Cheers,
Remco

**Comment by alexeid** [comment]
I would think that an easy solution is to let new versions of BEAUti add an optional (and therefore backwards compatible) list of <requires> elements at the top of the file as Simon suggests. 

If the <requires> elements are present then the user will get a nice clear message when the package is not installed and the program will halt. If the <requires> elements are not present in the XML and a required package is missing then the run will fail in the obscure way that it currently fails. But all newly created XMLs (and reloaded old ones) will have sensible messages. This could also eventually lead to automatic installation of packages (with user permission) if there is a <requires> in an XML that is not met.

**Comment by rbouckaert** [comment]
Sure, the problem remaining is to find out which packages are required by an analysis, which requires tracking the classes used in an analyses as well as tracking which packages provide these classes. The former requires a simple traversal of the graph, which is not hard. 

The latter requires a bit more thought: I suppose it is sufficient to just check all classes in the package/lib/package.addon.jar files, assuming that each package has its classes there. Where things get hairy is when more than one package include a library (say XYZ.jar) and there is some input of a type from such library. Then it requires XYZ.jar from package A or from package B, but it is not easy to determine which one to put in the `require` attribute (rather than element, we do not want any extra special XML elements that need explaining and special handling by the XMLParser). If we only consider classes from the package library, we have to rely on them being identifiable. The naming convention most (but not all, e.g. STACEY) packages are using is to have the library in package/lib/package.addon.jar.

As Tim brought up, another consideration is that package B can be dependent on package A, but only classes in package B end up in the analysis. In that case, package A and B are required, but only package B will be in the `require` attribute. If packages A and B are missing then installing package B will automatically get package A installed (or if not, will result in error messages at the start explaining package A is missing) so I don't think this is a big issue.

**Comment by rbouckaert** [comment]
Commit b435597d3af3e99da4b5c64c589d460989cb5f57 goes some way to solve this; package names and versions at the time the XML is produced by BEAUti is stored in the required-attribute on the beast-tag, e.g. like so:

    required="SA v1.1.5:bModelTest v0.3.2" ...

The XML Parser checks whether any of these packages is available. Since a TreeMap<String, Package> packages is constructed at AddOnManager.loadExternalJars(), it seemed good to keep that data structure around, so it was made static. @tgvaughan see any problem with this?

At the moment, it only warns when packages are not available, and the error mentioned by @SimonGreenhill  is now extended by warning about packages as well, if missing packages are detected.

Not sure what to do about package versions numbers yet; older packages then are in "required" may result in different behaviour than newer packages in "required". At the moment, package version numbers are ignored.

**Comment by SimonGreenhill** [comment]
Awesome, this will cover most of the problems I think. Great work, and thanks!

**Comment by rbouckaert** [comment]
by b435597. #91 deals with the more general case of running an analysis with the set of packages at exactly the required versions.
