### ISSUE TITLE
Covarion model does not work as advertised in other than BEAST mode

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#562]
The stationary frequencies when calculated in other than BEAST mode differs from the documentation. For mode=REVERSIBLE, this can be fixed by flipping s * f0 <=> s * f1 in the rate matrix, making it very numerically instable. Instead of getting stationary frequencies with [ p0 * f0, p1, * f0, p0 * f1, p1, * f1 ] it produces [ p0 * f1, p1, * f1, p0 * f0, p1, * f0 ] where p0,p1 are cognate frequencies and f0,f1 hidden frequencies. When run with f0=f1=0.5 these stationary frequencies are the same, which is how we mostly run this model.
The Tuffley Steel mode has its stationary frequencies broken as well. Fix: implement as documented. Even then, it turns out to be rather numerically unstable.

**Comment by alexeid** [comment]
Advertised where? Shouldn’t we implement a model that you can do effective inference with? Unless you mean that there is a specific paper that we are trying to implement that we have not implemented correctly.

**Comment by rbouckaert** [comment]
The comments at the start of the code advertise how the model is supposed to work. It now works that way, but the implementation is numerically instable. Using the RobustEigenSystem from the BEAST CLASSIC package goes some way to counter that instability.

**Comment by alexeid** [comment]
Personally I think an issue like this one can almost not be fixed without a paper. It sounds like a serious conceptual problem overlayed with a serious numerical problem. Or am I missing something? Can you please add more detail to the issue, specifically what your reference for “advertised” model is? The covarion model has been implemented and used for years, hasn’t it? Without doing some careful peer-reviewed testing we shouldn't make significant changes to core models, should we? Minimally we will need to make an announcement of the change, its scope and impact since all papers that have already used the covarion model are affected, right?

**Comment by alexeid** [comment]
We shouldn't just change the fundamental behaviour of a core model that has been used in multiple publications without a really really strong justification. Normally you at least need to publish a detailed reasoning and test results on a permanent web address and make an announcement to the beast-users forum. Better would be a peer-reviewed paper.

**Comment by lmaurits** [comment]
> all papers that have already used the covarion model are affected, right?

My understanding is that all papers that have used the Covarion model
with fixed hidden frequencies of (0.5, 0.5) are *not* affected.  The
fix only makes a difference when the frequencies are unequal.

> 
> > On 2/06/2016, at 3:22 PM, Remco Bouckaert <notifications@github.com> wrote:
> > 
> > The stationary frequencies when calculated in other than BEAST mode differs from the documentation. For mode=REVERSIBLE, this can be fixed by flipping s * f0 <=> s * f1 in the rate matrix, making it very numerically instable. Instead of getting stationary frequencies with [ p0 * f0, p1, * f0, p0 * f1, p1, * f1 ] it produces [ p0 * f1, p1, * f1, p0 * f0, p1, * f0 ] where p0,p1 are cognate frequencies and f0,f1 hidden frequencies. When run with f0=f1=0.5 these stationary frequencies are the same, which is how we mostly run this model.
> > The Tuffley Steel mode has its stationary frequencies broken as well. Fix: implement as documented. Even then, it turns out to be rather numerically unstable.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub <https://github.com/CompEvol/beast2/issues/562>, or mute the thread <https://github.com/notifications/unsubscribe/AA3WSfuJW40esekRzD_c-ORdbt_K1ITeks5qHkx0gaJpZM4IsK9h>.
> > 
> 
> 
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/CompEvol/beast2/issues/562#issuecomment-223188821

-- 
Luke Maurits <luke@maurits.id.au>

**Comment by alexeid** [comment]
Maybe that is the case, maybe not. I am not sure what length you have gone to determine that. Is it true that unequal hidden frequencies couldn’t be previously used even by editing the XML? I though Simon Greenhill had played with this previously?

The point is, the behaviour of models shouldn’t be changed in any material way once they are published and used. If behaviour is changed is needs to be extremely well justified and signposted. Comments on GitHub aren’t sufficient, since most users of BEAST are not programmers.

**Comment by jheled** [comment]
Here is a short summary I made about the Covarion model. [https://drive.google.com/file/d/0BxbPcmfTXtMiZ0NPMXNoS0k3bXM/view?usp=sharing](url)

**Comment by rbouckaert** [comment]
@jheled that links gives a 404 error for me.

**Comment by jheled** [comment]
I used the "Add a link" button. Probably does something I don't understand.  Just copy the link and paste
https://drive.google.com/file/d/0BxbPcmfTXtMiZ0NPMXNoS0k3bXM/view?usp=sharing

**Comment by alexeid** [comment]
works fine for me.

**Comment by lmaurits** [comment]
Works for me, too.  Thanks for this, Joseph, the detailed discussion of
rates/intervals was enlightening, for me anyway.

The matrix you propose at the top of page 2 is the same one that I
expected, which was different from the implementation in BEAST before
Remco's change.  The implementation now seems to match your description.

Am I right in thinking that the "issues" discussed here are basically
limited to the interpretation of the parameter values that you get out
of a completed analysis?

On Mon, 06 Jun 2016 14:32:23 -0700
Alexei Drummond <notifications@github.com> wrote:

> works fine for me.
> 
> > On 7/06/2016, at 9:09 am, Joseph Heled <notifications@github.com> wrote:
> > 
> > I used the "Add a link" button. Probably does something I don't understand. Just copy the link and paste
> > https://drive.google.com/file/d/0BxbPcmfTXtMiZ0NPMXNoS0k3bXM/view?usp=sharing <https://drive.google.com/file/d/0BxbPcmfTXtMiZ0NPMXNoS0k3bXM/view?usp=sharing>
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub <https://github.com/CompEvol/beast2/issues/562#issuecomment-224089245>, or mute the thread <https://github.com/notifications/unsubscribe/AA3WSUIE_DmTRZXCMNyh27tbf2xUwGegks5qJIyCgaJpZM4IsK9h>.
> > 
> 
> 
> 
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/CompEvol/beast2/issues/562#issuecomment-224095027

-- 
Luke Maurits <luke@maurits.id.au>

**Comment by alexeid** [comment]
If the instantaneous rate matrix Q has changed with Remco’s fix then one of two things must be true:

(1) We didn’t have a junit test that adequately tested for correctness of Q, nor for the correctness of P(t).

(2) We did have tests, but the original assumptions about the model disagree with the current assumptions (regardless of what the comments say).

Do we know which one is true? Do we now have adequate junit tests that determine both Q and P(t) are generated correctly?

If we do in fact end up agreeing that there was a bug in the implementation of Q, then we will need to do a proper announcement to beast-users and on beast2.org <http://beast2.org/> and alert all users that have done analyses with the covarion model to re-run them since their results may change.

The covarion is also implemented in BEAST1 so it would be a bit bizarre to have different implementations in the two packages.

**Comment by rbouckaert** [comment]
@alexeid  (1) is true. In commit 6d349fea81fdcd7edfe5c3203475b8a349406186 I added a tests for base frequencies for the three modes.

The default implementation (mode="BEAST", i.e. the BEAST1 implementation) has not changed with the that commit, and is only reversible if hidden frequencies are (0.5,0.5). Note that mode="REVERSIBLE" and mode="TUFFLEYSTEEL" are not available in BEAST1. Only analyses using these modes would be affected.

**Comment by alexeid** [comment]
right - but if somebody convinces me that mode=“BEAST” is wrong, then we shouldn’t support it at all right? If it was a bug...

**Comment by rbouckaert** [comment]
The good news is that mode=BEAST with hidden frequencies at (0.5,0.5) is equal to mode=REVERSIBLE. 

The bad news is that mode=REVERSIBLE with hidden frequencies not at (0.5,0.5) appears to be numerically instable, judging from the trouble I had setting up the unit test when randomly picking these frequencies. I have no idea whether there is a large stable range for hidden frequencies, but would not recommend this without further investigation.

**Comment by alexeid** [comment]
Okay. But if mode=BEAST with unequal hidden frequencies doesn’t make sense then should we mode=BEAST at all?
