### ISSUE TITLE
Running BEAST2 as a .jar with BASTA and MTT?

### ISSUE THREAD

**Issue by sidneymbell** [CompEvol/beast2#569]
Morning!

I'm trying to run BEAST2 as a `java -jar beast2.jar` so I can allocate more memory. I'm also running BASTA and MultiTypeTree. Nicola provides the following for running BEAST2 & BASTA as `.jar`s:

```java -cp [path-to-BASTA.jar]:[path-to-beast.jar] beast.app.beastapp.BeastMain [beast-command-line-options] [path-to-xml-input-file]```

Any guidance on how to also provide the MultiTypeTree `.jar`? 

Thank you so much for your time and assistance!

**Comment by jessiewu** [comment]
Hi,

I've managed to get it running with 

java -cp [path-to-beast2.jar]:[path-to-guava-15.0.jar]:[jblas-1.2.3.jar]:[MultiTypeTree.v6.2.0.jar] beast.app.beastapp.BeastMain [beast-command-line-options] [path-to-xml-input-file]

beast2.jar has version 2.4.0
guava-15.0.jar, jblas-1.2.3.jar and MultiTypeTree.v6.2.0.jar are in the lib folder in the zip bundle that you can download from the github release of the MultiTypeTree package
For [path-to-xml-input-file] I've used structuredCoalescent.xml which is also in the MultiTypeTree package zip bundle

**Comment by sidneymbell** [comment]
Thank you so much! I'll test it out this afternoon and let you know if I run into any issues.

**Comment by rbouckaert** [comment]
Hi Sidney,

If you install packages through the package manager, there is no need to include the complete path to package jars, since beast will find these jars when it starts up.
Just running 

`java -Xmx4g [path-to-beast.jar] [beast-command-line-options] [path-to-xml-input-file]`

should do the trick, where the -Xmx4g argument sets the memory allocation to 4GB. You could also just edit the scripts beast/bin/beast on OSX or Linux to assign more memory to java.

Hope this helps, Remco

**Comment by sidneymbell** [comment]
Thanks so much, all! I managed to get it running per Remco's suggestion; I didn't realize the beast.jar itself would keep track of the package.jar paths once installed. Thanks to you, too, jessiewu. Greatly appreciate the help.
