### ISSUE TITLE
Logger for tree length

### ISSUE THREAD

**Issue by z3nabi** [CompEvol/beast2#577]
As discussed with @tgvaughan today:

Currently the only tree summary statistic for which a logger is implemented in the BEAST core is tree height. I would like to also log tree length. Such a logger is already available in MultiTypeTree and can also be used in a regular BEAST analysis after the package has been installed which is an easy work-around. I still find that it could be part of the core.

**Comment by tgvaughan** [comment]
Tree length is a very good indicator of tree space mixing, so I second this.

**Comment by rbouckaert** [comment]
I already implemented this as optional output for TreeHeightLogger...

**Comment by tgvaughan** [comment]
Thanks Remco, although the name bothers me slightly now.  Can we maybe instead move this to TreeLengthLogger?  Or rename TreeHeightLogger to TreeStatsLogger and have it always log both? (We'd leave TreeHeightLogger in place but deprecate it.)

In any case, why not have the length logged by default?  This is a very useful parameter for assessing the tree space mixing!

**Comment by alexeid** [comment]
TL should be logged by default. It would be nice if the class was named sanely.

**Comment by rbouckaert** [comment]
For backward compatibility, we need to have TreeHeightLogger around for at least v2.4. How about we  deprecate this class and copy what is now TreeHeightLogger (with length logging) to TreeStatLogger, which allows adding more tree logging functionality that turns out to be essential later on. So, till v2.5 we have two classes around. This means any top level BEAUti templates need replacing TreeHeightLogger with TreeStatLogger, but we can already do this for Standard.xml and StarBeast.xml.

Pardon my ignorance, but what extra information does tree length provide over tree height for analysing tree space mixing?

**Comment by tgvaughan** [comment]
Hey Remco, good idea.  It just seems to be the case that the tree length mixes more slowly than the tree height - probably because it depends on more of the tree state than the height alone.  I've heard this from others too.

**Comment by alexeid** [comment]
The tree length is the sum of all branches -> It integrates convergence information from all the nodes in the tree and, roughly speaking, it mixes as slowly as the slowest node in the tree, wherever that is. 

The tree height is a function of a single node height -> it is sometimes is a good proxy for the rest of the tree and it sometimes does its own thing.

**Comment by rbouckaert** [comment]
Template files are not updated yet and still use the TreeHeightLogger -- there is a bit of work involved in getting all BEAUti junit and integration tests up to date now that tree length is logged by default there is an extra entry in the log file, which impacts the ordering of entries and junit tests need to be made aware of this.
