### ISSUE TITLE
Implement all named restrictions of GTR in beast2 core and BEAUti Standard template

### ISSUE THREAD

**Issue by alexeid** [CompEvol/beast2#597]
Many users still use jModelTest et cetera to chose substitutions models. This practice will not end soon. Currently the only way to implement many of these models (TIM, TIM2, TPM2uf et cetera) is to make direct changes to the XML which are error prone and break the reloading of the XML into BEAUti. We should implement these models directly in BEAUti to minimise user error and maximum usability.

**Comment by rbouckaert** [comment]
It is a bad idea to do this in the core for the following reasons;

1. it encourages bad practices while there are perfectly good Bayesian alternatives available such as bModelTest, RBS and substBMA.

2. it clutters the core. At the very least, this should be in BEASTlabs or even in its own separate package.

3. it clutters BEAUti by making a large number of choices available, which will intimidate novices. For that reason alone it should not be in the core, but in another package, so that people that still want to use it can make an informed choice having to select among the 10 or so named alternatives.

**Comment by alexeid** [comment]
(1) it supports standard practices. We both think there are better ways to do things, but I also believe in supporting industry standards.

(2) The core should do things that have been standard practice for many years. 

(3) The number of named models is small and manageable and widely understood since extremely popular packages such as jModelTest produce them as output.

**Comment by walterxie** [comment]
testing Remco's implementation in BEAST2-Dev/substmodels.

**Comment by rbouckaert** [comment]
The Standard Substitution Model (SSM) package is now released.
