### ISSUE TITLE
merge "+ button" and "drag drop" function

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#631]
But ideally the drag and drop action would call *exactly* the same single method as the result of the [+] button so that they would both work identically!

@alexeid
@genomescale

**Comment by genomescale** [comment]
The problem is not with Shae's XML. Any StarBEAST2 template will not initialize the population model if alignments are dragged-and-dropped instead of using the [+] button. This may be a bug in the SB2 templates which I haven't found yet, but is quite possibly a defect in BEAST2. If the problem is due to BEAST2, the fact that the bundled templates don't trigger the bug doesn't mean it's not a bug.

**Comment by walterxie** [comment]
"+ button" and "drag drop" are using the same method now.
