### ISSUE TITLE
NEXUS import can hang on missing semi colon

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#652]
As outlined [here](https://groups.google.com/forum/#!searchin/beast-users/SNAPP$20template%7Csort:relevance/beast-users/YHrnXSwREfQ/qmlnJW0_BwAJ), but it should fail gracefully, ideally reporting a suggestion to add a semi-colon to the file.

**Comment by tgvaughan** [comment]
I think there are (at least) two issues here that need to be addressed separately:

1. BEAUti seems to hang when it is still actually working.  This happens even when importing unbroken data files.  The real problem is that BEAUti uses the event dispatch thread to do real work, when the EDT should be doing only quick GUI-related stuff.  In order to keep the GUI responsive, worker threads should be used to handle BEAST model construction.  This is already the focus of issue #436 and maybe others as well.

2. Our Nexus parser is incomplete and fragile.  This is addressed in issues #30, #146 and #396.  In this case, it looks like the missing semicolon is causing the parser to do something computationally expensive before it catches the error.  We could maybe patch this specific problem, but I think it's likely that a more complete parser (e.g. JEBL's parser) could handle this sensibly as well as addressing all of the other related issues..

**Comment by rbouckaert** [comment]
There is an (incomplete) port of JEBL to BEAST2 [here](https://github.com/rbouckaert/jebl2).

JEBL's parser is not as complete as you think. For example, on the file [posted](https://groups.google.com/forum/#!searchin/beast-users/SNAPP$20template%7Csort:relevance/beast-users/YHrnXSwREfQ/qmlnJW0_BwAJ) on the user list it fails with the message

    DATA or CHARACTERS block is missing

while ideally it should report that a semi-colon was missing. When adding the semi colon, it produces the same message, and cannot parse the file at all, while the BEAST parser has no problem with it. IIRC there are other nexus files in the examples/nexus directory that do not parse either with JEBL's parser.

**Comment by alexeid** [comment]
We should definitely fix 1. That is a basic rule of GUI programming.

**Comment by tgvaughan** [comment]
Hi Remco, can't we maybe extend the JEBL parser to handle other datatypes? Agree that the error message from the missing semicolon is confusing, although missing delimiter errors are hard for parsers to spot.  (I've never had a C compiler that correctly diagnose a missing semicolon.) I think the best you could expect in this case is something along the lines of "Unknown argument to Format command".
The BEAST parser may actually be more robust wrt missing semicolons, as it actually just strips them and doesn't even use them as a delimiter - it uses newlines instead.

**Comment by rbouckaert** [comment]
Fixed by 2fbe73c.
For general Nexus issues there is now #30, which is labeled "Generic catch all issue", since I don't think we will ever reach a complete nexus parser.
