### ISSUE TITLE
Continue running with likelihood Infinity?

### ISSUE THREAD

**Issue by Anaphory** [CompEvol/beast2#656]
It can happen that the likelihood calculated by beast explodes to infinity, often because some conflict in the model specification combined with numerical instability lets some numbers explode.

What is the rationale behind letting beast continue to run in that case, instead of exiting with a unique return code?

**Comment by rbouckaert** [comment]
Testing for positive infinities makes sense -- even though NaN posteriors may be a sign of the same problem, testing for NaNs does not make sense, since when sampling from the prior, the likelihood will remain NaN and therefore the posterior will be NaN as well. So, stopping on NaNs will prevent sampling from the prior.
