### ISSUE TITLE
unknown discrete trait

### ISSUE THREAD

**Issue by ceya** [CompEvol/beast2#666]
Hello there,

I have 4 types of discrete traits for my taxa. For a few taxa, the exact state is known. Can BEAST still analyze the data for ancestral reconstruction? and what should be put in the trait column?

Thanks!

**Comment by rbouckaert** [comment]
This is with the ancestral reconstruction package from the BEAST_CLASSIC package, I presume.
You can specify ambiguous states in the user datatype. For example, the file H5N1_HA_discrete2.xml from the BEAST_CLASSIC package contains this datatype:

     <userDataType spec='beast.evolution.datatype.UserDataType' id='location' 
                states='7'
                codelength='-1'
                codeMap='
                Fujian = 0,
                Guangdong = 1,
                Henan = 2,
                HongKong = 3,
                Guangxi = 4,
                Hunan = 5,
                Hebei = 6,
                ? = 0 1 2 3 4 5 6,
                - = 0 1 2 3 4 5 6'
                />
If you are not sure whether a sample is from Fujian or Guangdong, you can add a new state FujianGuangdong which then can take values 0 or 1 like so:

     <userDataType spec='beast.evolution.datatype.UserDataType' id='location' 
                states='7'
                codelength='-1'
                codeMap='
                Fujian = 0,
                Guangdong = 1,
                FujianGuangdong = 0 1,
                Henan = 2,
                HongKong = 3,
                Guangxi = 4,
                Hunan = 5,
                Hebei = 6,
                ? = 0 1 2 3 4 5 6,
                - = 0 1 2 3 4 5 6'
                />

Make sure to set the useAmbiguities flag on the treelikelihood, otherwise the data is treated as missing data.

By the way, this kind of question is more appropriate for the [beast-user mailing list](https://groups.google.com/forum/#!forum/beast-users). This issues list are for registering bugs and code enhancements.
