### ISSUE TITLE
TreeAnnotator and rate info

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#692]
BEAST 1 adds rate information between colon and branch length, which is not handled by the tree parser, so BEAST 1 trees cannot be handled by TreeAnnotator2.

A tiny example: [dna.trees.txt](https://github.com/CompEvol/beast2/files/968600/dna.trees.txt)

The error message could use some help. It points to the wrong line and character position.

java.lang.RuntimeException: TreeParser cannot make sense of the Newick string provided.  It gives the following clue:
Error parsing character 4 of Newick string: mismatched input '[&' expecting {FLOAT_SCI, FLOAT, INT}
	at beast.util.TreeParser.initAndValidate(TreeParser.java:159)
	at beast.util.TreeParser.<init>(TreeParser.java:271)
	at beast.util.NexusParser.parseTreesBlock(NexusParser.java:170)
	at beast.util.NexusParser.parseFile(NexusParser.java:131)
	at beast.util.NexusParser.parseFile(NexusParser.java:92)
	at beast.app.treeannotator.TreeAnnotator$FastTreeSet.<init>(TreeAnnotator.java:132)
	at beast.app.treeannotator.TreeAnnotator.<init>(TreeAnnotator.java:466)
	at beast.app.treeannotator.TreeAnnotator.main(TreeAnnotator.java:1504)
java.io.IOException: Around line 11

**Comment by rbouckaert** [comment]
@tgvaughan This seems easily fixed by adding "meta?" after the colon in the grammar so it reads

post: label? meta? (':' meta? length=number)? ;

but I got stuck generating the java code. When I put antlr-4.5-complete.jar in the treeparser directory and do

java -jar antlr-4.5-complete.jar -package beast.util.treeparser NewickParser.g4 NewickLexer.g4

there are no warnings or errors and I get code in beast.util.treeparser that parses, but TreeParser does not compile any more due to this error:

"The method attrib() is undefined for the type List<NewickParser.MetaContext>	TreeParser.java	/beast2/src/beast/util	line 451"

What am I missing?

**Comment by rbouckaert** [comment]
Looks like the MetaContext changed type since instead of allowing a single meta data item the grammar now allows two, so instead of being a single object it now is a list. Iterating over the list solves the problem, but still leaves something else to be solved since the TreeParserTest still fails.

**Comment by tgvaughan** [comment]
Hey Remco,

Sadly it is quite impossible for TreeParser to give a better error message here. (If you remember, we spent an afternoon a while back trying to make these error messages as sensible as possible.) TreeParser only handles the "newick"  parsing - it is given the string starting at the open parenthesis on line 17 and doesn't know anything about where this string came from or its position in a file.  The problem character is 4 characters into this string, hence the report.  What needs to happen is for this exception to bubble up to TreeAnnotator which can do some sensible reporting.  It's strange that TA gets the line wrong. I'll look into this.

Regarding the parsing of this file, yeah it generates an error because it violates the grammar.  I'm sure I've asked this before, but is there an existing EBNF grammar for BEAST tree blocks?  I'm only aware of the ones that I've put together, both as ANTLR parsers and on the [MASTER wiki](https://github.com/tgvaughan/MASTER/wiki/Annotated-Network-and-Tree-grammar).  I'm just worried that there are maybe other important things like this that we're missing from both the grammar and the parsing unit tests, which is an embarrassing situation to be in!

If you push the code you've been working on I can have a peek at it and see if I can convince it to work.. :-)

**Comment by rbouckaert** [comment]
Hi Tim, just submitted the code as far as I could get it working. Would be great if you can have a look at what still goes wrong.

**Comment by tgvaughan** [comment]
81681eb fixes the line number estimation problem at least.  There were a couple of block processing methods in NexusParser that weren't incrementing the line number counter.

**Comment by tgvaughan** [comment]
Hey Remco, looking at your update it seems as though you're assigning the metadata following ':' to the Node using Node::setMetaData, just as we do for the regular metadata.  Is this wise?  What happens if a node annotation and an edge length annotation have the same key?

**Comment by rbouckaert** [comment]
I suppose the last entry wins, but I'm not sure whether there is a reasonable scenario for having key duplicates. Isn't that what happens at the moment when there are duplicate keys inside the same metadata block?

**Comment by alexeid** [comment]
Branch annotations and node annotations are logically different in general, so I would support an implementation that recognizes that. Since they are logically different, it would be conceivable to have the same label within the two different scopes actually refer to distinct data. To see that distinguishing the two types of metadata can be vitally important see, for example, this recently exposed problem with branch support values being interpreted as node attributes when in an unrooted tree they are in fact branch attributes. It causes chaos after re-rooting if they aren’t treated logically as branch attributes:

http://biorxiv.org/content/early/2015/12/25/035360

**Comment by tgvaughan** [comment]
Given the way they're expressed in Remco's grammar, it seems that these are branch _length_ annotations, not true edge annotations: they cannot occur on edges that don't have a length.  It's not immediately obvious how to change this without using a different Newick base grammar since in Newick a colon must always be followed by a number (see [here](https://en.wikipedia.org/wiki/Newick_format) for instance).

**Comment by tgvaughan** [comment]
If we want to keep these logically separate, the best thing to do is to add names to the elements in the rule:

    post: label? nodeMeta=meta? (':' lengthMeta=meta? length=number)? ;

This means that the visitor can simply query postCtx.nodeMeta and postCtx.lengthMeta separately.

**Comment by rbouckaert** [comment]
@alexeid  since BEAST exclusively uses rooted time trees, the issue mentioned in the paper may not.
If this needs fixing, it will have consequences for how a Node represents its metadata and for how TreeAnnotator labels a tree as well.
Regardless, a bigger problem is that making small changes to the grammar leads to code that stops functioning, and I'm not sure how to fix this...

**Comment by rbouckaert** [comment]
@tgvaughan regarding grammars for NEXUS trees, I am not aware of any, but for Newick trees without meta-data there is one on [wikipedia](https://en.wikipedia.org/wiki/Newick_format). NEXUS allow comments in brackets everywhere, so the easiest way to do interpret metadata was by interpreting any comment sufficiently close to where the node is specified as such and pares key-value pairs. This is what the old parser did, and that parser has no problem with BEAST 1 trees.

**Comment by tgvaughan** [comment]
Is it possible to express "sufficiently close" in EBNF?

**Comment by alexeid** [comment]
There are only two places that metadata can occur in trees generated by BEAST 1 and readable by FigTree, before or after the “:”.

Node attributes are put before the colon: 

<node>[&height=100.0]:<branch_length>

Branch attributes are put after the colon: 

<node>:[&bootstrap=75.0]<branch_length>

https://web.archive.org/web/20130129042404/http://code.google.com:80/p/beast-mcmc/wiki/NexusMetacommentFormat

**Comment by tgvaughan** [comment]
Thanks Alexei, that clears it up.  Embarrassingly I have visited that metacomment page before, so there's no excuse for this not already being in the grammar.  Sorry everyone!

**Comment by tgvaughan** [comment]
I've added *LengthMetaData methods and fields to Node to support this.  The newick string generated from trees parsed in from Remco's example reproduce the edge length metadata in the correct spot.

**Comment by rbouckaert** [comment]
Good -- out of curiosity, any idea why the solution I submitted failed?

**Comment by tgvaughan** [comment]
BTW Remco, a neat trick with ANTLR grammars is that you can give rule elements names.  So I changed your modified to:

    post: label? nodeMeta=meta? (':' lengthMeta=meta? length=number)? ;

This gives the post context object `postCtx` the new fields `nodeMeta` and `lengthMeta` that hold the contexts for each of the corresponding meta elements.  This made it trivial to process and add to the appropriate Node fields.

**Comment by tgvaughan** [comment]
@rbouckaert The unit tests failed because the updated code was setting node.metaDataString to non-null even when no metadata existed.  The original code had:

```java
            if (postCtx.meta() != null) {

                node.metaDataString = "";
                for (int i=0; i<postCtx.meta().attrib().size(); i++) {
                    if (i>0)
                        node.metaDataString += ",";
                    node.metaDataString += postCtx.meta().attrib().get(i).getText();
                }

                // etc
```
which meant that node.metaDataString remained null when the input tree had no metadata.  Your update looked like this:

```java
            if (postCtx.meta() != null) {
                        node.metaDataString = "";
                        for (MetaContext attr: postCtx.meta()) {
            	            for (int i=0; i<attr.attrib().size(); i++) {
            	                if (i>0)
            	                    node.metaDataString += ",";
            	                node.metaDataString += attr.attrib().get(i).getText();
            	            }

                           // etc
```
Since postCtx.meta() now returns a (potentially empty) list, this was always non-null.  This screwed up the newick generator, which inserts the Node.metaDataString into the output tree surrounded by `[&` and `]` whenever Node.metaDataStrings is non-null.  So the output newick trees were peppered with '[&]' strings, which caused comparison failures in the tests.

**Comment by tgvaughan** [comment]
(An easy fix would have been to just replace the `postCtx.meta() != null` with `!postCtx.isEmpty()`.)

**Comment by rbouckaert** [comment]
@tgvaughan thanks for digging this up! It looks like it was all in the post-processing.
