### ISSUE TITLE
TreeAnnotator.cmd cannot run

### ISSUE THREAD

**Issue by wpwupingwp** [CompEvol/beast2#695]
@echo off
setlocal
if ""=="%BEAST%" set BEAST=%~dp0%..
set BEAST_LIB=%BEAST%\lib
java -Xms64m -Xmx256m -Djava.library.path="%BEAST_LIB%" -cp "%BEAST_LIB%\beast.jar" **beast.app.treeannotator.TreeAnnotator** %*
pause

**Comment by wpwupingwp** [comment]
It still use path in BEAST 1.8.4 and says cannot find TreeAnnotator. Change to path above then ok.

**Comment by rbouckaert** [comment]
Which OS are you using? Does the last sentence suggest you fixed the problem?

**Comment by wpwupingwp** [comment]
Windows 10.
The original line is
"dr.app.tools.TreeAnnotator", which is path in BEAST 1

**Comment by rbouckaert** [comment]
For Windows, there is a TreeAnnotator.exe application that you can use to start TreeAnnotator. The exe file is packaged with BEAST for Windows, so there is no need for a separate batch file, unless you need to change the memory settings. However, by default there is 4GB of heap reserved in TreeAnnotator.exe, which is more than in the batch file.

**Comment by wpwupingwp** [comment]
That's why I use TreeAnnotator.cmd, my data need 10+ GB memory :)

**Comment by tgvaughan** [comment]
Sorry @wpwupingwp, it's not clear to me what the issue is here.  Are you reporting a bug? What is this TreeAnnotator.cmd?  Is this something that is distributed with BEAST 1?  If so, it makes sense that it doesn't work with BEAST 2 out of the box, because the class locations are different.  It isn't distributed with BEAST 2 at all, so this can't be a bug in BEAST 2.

If I've misunderstood and you are reporting some other problem, please let us know.  Otherwise I'm afraid we will have to close the issue.

**Comment by wpwupingwp** [comment]
Sorry, I think I downloaded wrong version of BEAST2.
