### ISSUE TITLE
Tree(final Node rootNode) needs to copy root

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#705]
@alexeid @rbouckaert @tgvaughan 
`Tree(final Node rootNode)` currently is reusing the reference of given `rootNode` instead of duplicating the tree. This does not matter if not changing the tree topologies, but will cause a lot of troubles if changing the root or nodes, because the "copied" tree is also changed unexpectedly. This unexpected behaviour makes me confused with my imported `FlexibleTree` code for the whole day yesterday.

I think it is a bug, any comment?

**Comment by tgvaughan** [comment]
This is the expected behaviour of this constructor, but you're right - it is potentially confusing and should some javadoc describing what it does.  The idiomatic BEAST 2 way of creating a new tree by simulation is to use some recursive procedure to construct a Node hierarchy and then use this constructor to wrap the new root node in a Tree object.  In contrast, copying a Tree can be done using Tree::copy (which performs true deep copy) or, which is basically equivalent to `new Tree(oldTree.getRoot().copy())`.

Definitely add some javadoc to the Tree constructor though: if it confused you, it will confuse others.

**Comment by rbouckaert** [comment]
Agreed.

**Comment by tgvaughan** [comment]
@rbouckaert with whom do you agree? :-)

**Comment by alexeid** [comment]
I agree with Tim’s response.

**Comment by rbouckaert** [comment]
@tgvaughan that would be you, Tim :-) (was in the process of writing what you wrote when it showed up on screen).
