### ISSUE TITLE
BEAUti fails when setting negative value for shape parameter of Gamma distribution

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#731]
The prior panel looks all weird after doing this, because it tries to set an illegal negative value and the exception that is thrown is not properly handled.

**Comment by tgvaughan** [comment]
This is kind of what I was getting at in #728.  While it's probably (hopefully) easy to fix this particular problem, it'd be great if we could find a way to handle all model configuration errors in a way that the BEAUti-level response is meaningful for users.  Otherwise we'll forever be playing this annoying game of wack-a-mole.

**Comment by tgvaughan** [comment]
I've modified the graph drawing code so that breaking exceptions are caught in one place so that the following error notification can be displayed instead:
<img width="923" alt="screen shot 2017-10-16 at 14 50 20" src="https://user-images.githubusercontent.com/512538/31612889-9f51e30e-b281-11e7-969f-cc06e0b20b5b.png">
Of course, it'd be great to have an actual error displayed next to the parameter causing the problem, but it seems that those errors are only produced when the value given is invalid for the input type (which a -ve value is not - it's invalid for the target of the input, i.e. the distribution object).  That should be raised as a separate issue though.
