### ISSUE TITLE
TreeParser produces more internal node labels than expected

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#734]
When parsing a tree like so: new TreeParser("((xmr),((knw)ctm))", false, true, true, 0, false);
both the parent of node "xmr" and that of "knw" have ID="ctm", while only the parent of "knw" should have its ID specified, and the parent of xmr should have ID=null.

**Comment by tgvaughan** [comment]
This isn't strictly a TreeParser issue.  What's going on here is that TreeParser calls Tree::initAndValidate at some point after the tree has been created in order to do trait processing etc.  Right at the end of this method we have the following code:

```java
// ensure all nodes have their taxon names set up
String [] taxa = getTaxaNames();
for (int i = 0; i < getNodeCount() && i < taxa.length; i++) {
    if( taxa[i] != null ) {
        if( m_nodes[i].getID() == null ) {
            m_nodes[i].setID(taxa[i]);
        }
    }
}
```

The `getTaxaNames` method returns an array containing all non-null node names.  Implicit in the loop below is the assumption that only leaves are labelled, since in this case the index of the node name in the array can correspond to the nodeNr of the node with that label.  This assumption does not hold for the test tree.  The "ctm" label has index 2 in the list, which is not the node number of the node which should have this label.  By chance, this is the node number of the parent of xmr, which is then also assigned the "ctm" label by the loop.

**Comment by tgvaughan** [comment]
Modified `getTaxaNames()` to skip non-leaf labels when producing the array.  Obviously this is short-sighted, but it's better than assigning internal node labels incorrectly.

**Comment by rbouckaert** [comment]
Thanks for the quick fix!
