### ISSUE TITLE
BEAUti SiteModelInputEditor DeltaExchangeOperator init exception

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#740]
@rbouckaert 
Hi, Remco,

There is an exception in the debug model, when the "Site Model" in BEAUti is selected at the first time after loading an alignment.

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	...
	at beast.evolution.operators.DeltaExchangeOperator.initAndValidate(DeltaExchangeOperator.java:126)
	at beast.core.BEASTInterface.initByName(BEASTInterface.java:103)
	at beast.app.beauti.SiteModelInputEditor.init(SiteModelInputEditor.java:78)
...

The bug is that DeltaExchangeOperator is not initialised with "parameter" in line 78 in SiteModelInputEditor.java. It is solved when I add the following code `, "parameter", new RealParameter(new Double[] { 1., 1., 1., 1. })` to `operator.initByName( ...  `.

Cheers,
Walter

**Comment by walterxie** [comment]
@rbouckaert
Hi, Remco,

Just realise your comment "ignore initAndValidate exception". I reverted my change.

Cheers,
Walter

**Comment by alexeid** [comment]
Surely it is not impossible to fix this? We shouldn’t let non-exception exceptions become part of the software design… These sorts of things usually point to a place where the design could be improved, don’t they? @rbouckaert could maybe explain it to us on Thursday?

**Comment by tgvaughan** [comment]
It'd be great if we could fix this.  I've had this particular error message listed in my [beauti template hacking notes](https://github.com/tgvaughan/feast/wiki/BEAUti-2-template-creation#snafu-expected-errors) specifically because I've lost hours believing one or other of my templates was at fault when actually the Standard template produces the same thing.  I don't understand the internals of beauti well enough to do this myself though.
