### ISSUE TITLE
How would recombination influence the dating result

### ISSUE THREAD

**Issue by thkuo** [CompEvol/beast2#743]
Hi,
My project focuses on the transmission of a bacterial population. We so far already obtained a phylogeny, and because of the frequent recombination events in the population, we also found a tool (ClonalFrameML) to correct the branch lengths. The question now is we are not so sure whether dating the tree before or after the correction of branch lengths is more proper. Can you please give some suggestions?

**Comment by tgvaughan** [comment]
Dear @thkuo, ideally you'd want to infer the dates under a model that also took into account recombination, and we have a beast2 package [bacter](https://tgvaughan.github.io/bacter) which does precisely this.  This is a beast2 implementation of the ClonalOrigin model but with extensions which allow joint inference of the clonal frame.

In future, it'd be great if you could post further questions to the beast mailing list (beast-users@googlegroups.com) instead of raising issues here.  This web page is really only for reporting bugs in beast and for feature requests.  Thanks!

**Comment by thkuo** [comment]
Many thanks!
