### ISSUE TITLE
ANTLR runtime library upgrade will cause dependency hell

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#744]
The uprgade to v4.7 of the runtime introduces an antlr API change.  Due to shared namespace issues, this is very likely to cause problems. (E.g. a handful of packages depend on/include my "feast" library, which uses the 4.5 API.) Given that there was really no real practical advantage to upgrading in the first place, my vote is to revert to 4.5.

**Comment by rbouckaert** [comment]
Hi Tim, Since the next BEAST release will be a major release (v2.5.0) I thought this would be a good time to update our libraries.  I already went trouble updating all my packages build.xml files and package specific beast start scripts to use v4.7 instead of v4.5, so am keen to use the latest libraries. I suppose this would be a good time to update commons-math and others as well.

**Comment by tgvaughan** [comment]
Hi Remco, sounds like a great idea.  I suppose I can just build my packages against the earlier code in the meantime, as otherwise they won't work with the current release.

**Comment by tgvaughan** [comment]
Newer version now back in place.
