### ISSUE TITLE
Reliance on internally provided XML parser library breaks compatibility with JDK 9

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#749]
The beast class `XMLParserUtils` [imports](https://github.com/CompEvol/beast2/blob/deacdc96496ae524c3a950604a38bf1a292f2360/src/beast/util/XMLParserUtils.java#L25) and [uses](https://github.com/CompEvol/beast2/blob/deacdc96496ae524c3a950604a38bf1a292f2360/src/beast/util/XMLParserUtils.java#L120) the class `com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl`.  During builds using the 1.8 JDK, this use generates the following warning:

    warning: CoreDocumentImpl is internal proprietary API and may be removed in a future release

It seems that with the 1.9 JDK this removal has finally occured, and the beast build fails as a result.

As this class is actually part of [Apache Xerxes](https://xerces.apache.org/xerces-j/) - an Apache XML parsing library - a simple way around the issue is to simply include this library with beast.  This seems to work, and in my experiments allows beast to once again be able to be built with the latest JDK.

(BTW, is this the only thing standing between us and compatibility with version 9 of the JRE?)

**Comment by rbouckaert** [comment]
I prepared a build that included the Xerxer libraries and its dependencies in the hope of getting it into the v2.4.8 release, since it would be nice to have this Java 8 dependency sorted. On OS X, the code that is supposed to check the JDK version fails (it thinks it is version 0, not 9) and when starting from a terminal, this message is shown:

Checking out /Users/remco/Library/Application Support/BEAST/2.4/BEAST/lib
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at beast.app.beastapp.BeastLauncher.checkForBEAST(Unknown Source)
	at beast.app.beastapp.BeastLauncher.loadBEASTJars(Unknown Source)
	at beast.app.beauti.BeautiLauncher.main(Unknown Source)

BEAST starts, but fails to load packages. I suspect the main new feature of Java 9 (Java Platform Module System) makes the way we load classes in Java 8 redundant, so there are more problems than just the dependency on CoreDocumentImpl.

**Comment by rbouckaert** [comment]
Further to this, it appears that javac cannot compile java 9 source code to java 8 (understandably, given new features in java 9), so if it may be more robust to stay with java 8 and fix code to deal with updates in java 9. Issues I found so far:
1. as Tim pointed out, com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl was removed. Adding the xerxes library will fix this -- is there a Java 9 alternative? 
2. Launcher.javaVersionCheck calls System.getProperty("java.version") which with java 9 return "9.0.0" instead of the less similar "1.8.0". Easy to fix.
3. AddOnManager.addURL calls clu.getClass().getClassLoader(), which used to return a URLClassLoader, but now returns a jdk.internal.loader.ClassLoaders$AppClassLoader. Not sure yet how to work around this.

**Comment by tgvaughan** [comment]
Goodness me.  Thanks for looking into this Remco.  Perhaps we should create a Java 9 "milestone" or something and group all related issues together there.

Luckily Java 8 is still the default JRE version offered at java.com, although the JDK has already switched of course.

**Comment by rbouckaert** [comment]
I am certainly aiming for 2.5.0 to be Java compliant. I expect there will be some unexpected issues popping up, since having the launcher create the class path means a big change. I am afraid that most of the functionality of the AddOnManager will need to be available for the launcher (e.g. updating packages on Windows at restart). Perhaps it is sufficient to just rename this issue to be the catch-all for Java 9 related problems.

**Comment by rbouckaert** [comment]
OS X has a special issue in that the Java 9 version of com.apple.eawt.AboutHandler appears to be incompatible with that of Java 8. Work around: do not use the about-handler in BEAUti for now. This makes BEAST/BEAUti compatible with Java 9 on OS X at least.

**Comment by rbouckaert** [comment]
The launchers (for BEAST, BEAUti, TreeAnnotator, etc.) now store a class path in beauti.properties at startup, provided no package.path is present in beauti.properties. When a package is installed through the package manager, the package.path is removed, and next time a launcher starts, it is restored.

Packages installed by hand have to remove the package.path by hand. An easy short-cut is to do this through BEAUti menu File/Clear class path.

Hope this is sufficiently robust/easy to use...

**Comment by rbouckaert** [comment]
When upgrading v2.5.0 to v2.5.X some time in the future, this can be done via the package manager, but there is only one entry for the BEAST package, so v2.4.X would upgrade to v2.5.X as well. Since v2.4.X and v2.5.X launchers load packages differently, installing a v2.5.X BEAST on a v2.4.X launcher would result in packages not being loaded. This is easily fixed by letting v2.5.X use its own separate package repository, and packages2.5.xml is already in CBAN, so that makes a good alternative.
