### ISSUE TITLE
BEAST 2.5.0 apps won't run (macOS 10.13.4; Java 9.0.4)

### ISSUE THREAD

**Issue by ReneMalenfant** [CompEvol/beast2#771]
Hi.

Using BEAST 2.5.0, if I double-click on any of the apps, they bounce once in the dock and then disappear.  I have tried both the standard install and JRE-packaged install of BEAST 2.5.0 and neither will work on my computer.  The only exception is DensiTree, which runs fine.  

If it matters, I have Java 9.0.4 installed, but I also have Apple's version of Java 6 ( https://support.apple.com/kb/dl1572 ), which is required for some legacy apps.  Is it possible that BEAST is detecting the wrong JRE?  (Apple's version of Java 6 installs itself into the PATH at /usr/bin/java, whereas Java 9.0.4 installs itself into /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java)

I could be wrong, but I don't think this is a Gatekeeper issue, because I have my Security & Privacy settings set to "Anywhere", and there is no message indicating that the BEAST apps were blocked by Gatekeeper.

**Comment by rbouckaert** [comment]
Do you have the JDK or JRE installed? On OS X, when installing the JRE instead of the JDK, it will not always be made the default Java version, and Java 6 (which comes with OS X) will be the default, which might explain why BEAST does not start.
To test this, open a terminal and type `java -version` to see which version it is. If it is 9.0.4, can you try 

`/Applications/BEAST\ 2.5.0/bin/beauti`

in the terminal and see what is reported?

**Comment by ReneMalenfant** [comment]
Thanks for the reply.  Just the JRE for Java 9 installed, I think.

The default version of Java is the version of Java 6 installed in the PATH:
```
[rene]% which java
/usr/bin/java

[rene]% java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

[rene]% /Applications/BEAST\ 2.5.0/bin/beauti
[java, -Djava.library.path=/Applications/BEAST 2.5.0/lib, -cp, ::/Users/rene/Library/Application Support/BEAST/2.5/BEAST/lib/beast.src.jar:/Users/rene/Library/Application Support/BEAST/2.5/BEAST/lib/beast.jar:/Applications/BEAST 2.5.0/lib/launcher.jar:/Applications/BEAST 2.5.0/lib/beast.src.jar:/Applications/BEAST 2.5.0/lib/beast.jar, beast.app.beauti.Beauti, -capture]
Exception in thread "main" java.lang.UnsupportedClassVersionError: beast/app/beauti/Beauti : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
java.lang.UNIXProcess$DeferredCloseInputStream@525c7734
```

**Comment by walterxie** [comment]
BEAST 2 requires Java 1.8 or higher. Your default Java version is 1.6, even though you have Java 9 installed.

**Comment by rbouckaert** [comment]
There is a Java version check, which obviously fails for some reason that I will investigate. The problem is that the default version of Java is 6. If you install the JDK instead of JRE, it automatically makes it the default version (for JDK 1.8 at least, which is available from http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html, I assume it is the same for JDK 9).

I will investigate why the version with JRE included does not work. Thanks for the bug report.

**Comment by ReneMalenfant** [comment]
Thanks.  I can confirm it does work if I install the JDK.

**Comment by rbouckaert** [comment]
Thanks for the confirmation -- I tested on OS X 10.13.1 and can confirm the with JRE version does not pick up the bundled JRE when the JDK is uninstalled.
