### ISSUE TITLE
2.5.0 Tip Date issue

### ISSUE THREAD

**Issue by springerbrowne** [CompEvol/beast2#779]
Hey,
I just downloaded the new 2.5.0 and setup an xml file and was getting an odd error about a sequence that wasn't even in the alignment.

I use a "master" tip date list, and BEAST2 has always been smart enough to grab the sequence names that match and autoconfigure them to that alignment.  In 2.5.0, it looked fine in Beauti, but the XML file is actually adding ALL the sequence names and dates from my "master" tip date list (rather than just the ones for that alignment).

I know this is slightly lazy on my part...but it was very convenient in the older versions of BEAST2 (I just grabbed 2.4.8 and it worked perfectly).  I've uploaded the xml file (compare the 47 sequences in alignment, to about 300+ listed in the tip date portion).

Just a heads up...keep up the awesome work!
[ST29.txt](https://github.com/CompEvol/beast2/files/1994019/ST29.txt)

**Comment by tgvaughan** [comment]
Thanks @springerbrowne, this is a good point and it should be straight-forward to fix.

**Comment by tgvaughan** [comment]
While the fix was straightforward, the most parsimonious implementation was to alter the way GuessPatternDialog stores and returns the trait values read from the file.  Previously, GuessPatternDialog used values read from the trait file to construct a trait string of the form expected by BEAST: "taxon1=val1,taxon2=val2,...".  The TipDateInputEditor would then retrieve this string and assign it directly to the relevant TraitSet object input.

Springer's problem arose because we recently (in 2.5) switched away from subsequent reparsing of this string, as this duplicated date format parsing already present in the TraitSet class.  This meant that the subsequent filtering which was stripping out the taxa not present in the alignment was no longer being performed.

What I've done now is to stop GuessPatternDialog from assembling the comma-delimited string.  It now stores the result of reading the trait file in a Map<String,String> and returns this.  The TipDateInputEditor can then easily ignore entries that are irrelevant and construct the comma-delimited string itself (as it does already in other cases).

This also makes another part of the code cleaner: TaxonSetInputEditor, which also relies on the output of GuessPatternDialog, was previously re-parsing the trait values from the comma-delimited string to generate it's own Map<String,String>.  Now it just reads this map directly from GuessPatternDialog, just as TraitSetInputEditor does.
