### ISSUE TITLE
Mean of log-normal prior distribution is not updated when an offset is used

### ISSUE THREAD

**Issue by ReneMalenfant** [CompEvol/beast2#788]
As seen in the following dummy example for a log-normal prior, if you use an offset when setting your priors, then the mean that is displayed reflects the mean of the original distribution, not the offset distribution.  The five-number summary and the x-axis of the figure are fine, but the mean is not.

<img width="1052" alt="prior" src="https://user-images.githubusercontent.com/12302720/41517613-b0803ea6-7292-11e8-81dc-43dcbb2e3c07.png">

**Comment by tgvaughan** [comment]
Thanks for noticing and reporting this René.

**Comment by tgvaughan** [comment]
Is fixed in master branch now:
<img width="993" alt="screen shot 2018-06-18 at 10 34 52 am" src="https://user-images.githubusercontent.com/512538/41526080-525509be-72e3-11e8-95cc-2e8bb7deec58.png">

It turns out that a couple of other distributions (eg `Poisson`) had this issue.  This was because each ParametricDistribution implementation was responsible itself for incorporating the offset into the mean.  Apparently some implementors forgot or did not know this.  To fix this I've therefore made `ParametricDistribution` child classes responsible only for implementing `getMeanWithoutOffset()` and having the offset added by the (final) method `getMean()` implemented in the parent class.
