### ISSUE TITLE
Sample from Prior command line flag

### ISSUE THREAD

**Issue by SimonGreenhill** [CompEvol/beast2#789]
It would be very handy to have a command line flag to set sampleFromPrior to true (much easier than editing the xml) e.g.:

```
beast2 -prior my.xml
```

**Comment by tgvaughan** [comment]
If user-defined variables could take default values, we could cause BEAUti to generate XMLs with something like
```xml
<run spec="MCMC" sampleFromPrior="$(prior|false)"/>
```
 to allow for something like `beast2 -D prior=true my.xml`.

This would be better than a hard-coded solution I think, because BEAST is actually much more general than an MCMC sampler: it only becomes one when fed specific XMLs.

**Comment by tgvaughan** [comment]
For the record, I don't like the idea I put forward above anymore.  It is challenging to get BEAUti to produce this output, and I think for good reason.  Perhaps a hard-coded solution is better after all.
