### ISSUE TITLE
Commas in BEAST argument values

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#792]
The -D option for BEAST is a comma separated string of name=value pairs. Consequently, commas are not allowed in values. Trying to replace them with &comma; or $#44; entities does not fix this problem. Consequently, currently it is not possible to replace a range of a plate.

All these:
`/path/to/beast -D "range=COI,ND2,CYTB" myxml.xml`
`/path/to/beast -D "range=COI&comma;ND2I&comma;CYTB" myxml.xml`
`/path/to/beast -D "range=COI&#44;ND2&#44;CYTB" myxml.xml`
fail (would be useful to add to http://www.beast2.org/2018/06/27/xml-tricks.html).

**Comment by tgvaughan** [comment]
We could perhaps leave the delimitation to the shell by only allowing a single key=value pair following -D,  but allowing multiple -Ds.  So instead of
```
beast -D "key1=val1,key2=val2"
```
you'd use
```
beast -D key1=val1 -D key2=val2
```
in a similar way to the property definitions are passed to the jvm.  Then you could just use standard quotes and shell escapes to include special characters, and you'd have no trouble with commas.

**Comment by rbouckaert** [comment]
@tgvaughan very much like that idea, but for backward compatibility we still need to support `-D "key1=val1,key2=val2"`, so when processing a -D argument, first count the number of '=' and ',' characters before deciding to split.

**Comment by rbouckaert** [comment]
Perhaps we can drop the multiple -D argument and use

`beast -D "key1=val1" "key2=val2" xyz.xml`

This requires making sure the next key/value pair does not start with a '-', and contains a '=' (otherwise it must be the last argument representing the file name).

Still have to deal with entities in values, which currently interfere with regular expression interpretation.

**Comment by tgvaughan** [comment]
@rbouckaert that's an intresting alternative, but aren't you worried that this is a bit too ambiguous?  While it's always possible for crazily named files to mess with option parsing (e.g. an XML file named '-D' in the current directory), I think it's actually feasible that somebody might include an '=' character in their filename.  And although this is less important, I also think this violates the [IEEE standard](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html) for command line options: "option-arguments should not be optional".

Maybe we should just go with the original syntax, but only split the key-value pairs on the last comma before the next key and forbid keys from including commas (which is sensible anyway).  Then sanitize the input prior to pasting it into the XML (using the existing sanitization method), meaning that entities are unnecessary.  Would this work?

**Comment by tgvaughan** [comment]
That commit allows `-D keyA=a,long,value,keyB=another,value`.  I really think this should just be a stop-gap though, as that command line argument is very hard to read.  At least it's backwards-compatible though.

**Comment by tgvaughan** [comment]
@rbouckaert the above is a rough attempt at implmenting the multiple -D idea.  It'd be great if you could at some point glance over this to make sure that I haven't broken anything!  Feel free to roll back if it does.  (There's a bit of code there as I had to introduce multiple option support to the Arguments class.)

**Comment by rbouckaert** [comment]
@tgvaughan Happy with the solution! Not quite following what happened to the Argument class, but in an ideal world that should be replaced by Input (as in the Application framework in BEASTLabs) anyway, where a Input<List<String>> could be used for handling multiple arguments.

**Comment by tgvaughan** [comment]
The changes look much more extensive in GitHub's diff view than they actually are: the mess in Arguments is mostly due to having to wrap the option handling code in a loop, meaning everthing inside gets indented and diff picks it up as being a change.  A word-diff would be helpful in this case.  

Really all I did was replace the `findArgument` method with `findArguments` and have it return List<Integer> instead of int, then loop over these results in the body of the `parseArguments` method.  I also added a flag to the `Option` class indicating whether the option could appear multiple times, and added an additional List<String> field to the `StringOption` class to store any additional values.  (Ideally the changes would all be made in Option with nothing specific to StringOption, but by doing it the way I've done it we avoid breaking the existing Arguments public API.)
