### ISSUE TITLE
BEAST 2.5.0->2.5.1 upgrade from BEAUti currently not possible

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#821]
Currently the package manager does not allow upgrades to BEAST 2.5.1.  Looking at [packages2.5.xml](https://github.com/CompEvol/CBAN/blob/master/packages2.5.xml) in CBAN it's clear that this is because there isn't an entry for this release.  I attempted to add one (commented out now), but the user on this end who was keen to upgrade found that the upgrade process from 2.5.0 to 2.5.1 didn't complete (Ubuntu).

I'd appreciate anybody who's familiar with the intricacies of the core package upgrade process having a peek.  Thanks!

**Comment by rbouckaert** [comment]
Yes, this is not a very satisfactory situation. It is this way because the majority of the upgrade to v2.5.1 is in the launcher, and the launcher cannot be updated other than by installing the full v2.5.1 release. It will probably cause problems when v2.5.2 comes out, but if automatic update via the package manager for v2.5.1 would be allowed it will be a nightmare to find out when things go wrong due to the launcher not being updated + any benefits from updating the beast.jar file are rather minimal.

**Comment by tgvaughan** [comment]
Ah, I see.  Maybe we could still make the package manager aware of the new version somehow?  Then BEAST could still make users aware of the new version but send them to the website to install in the instances that the launcher needed to be updated.

**Comment by tgvaughan** [comment]
Given this is no longer about 2.5.0->2.5.1 I'll close this issue.  We can open another to discuss improvements to the upgrade system at some point.

**Comment by rbouckaert** [comment]
I like the idea of the launcher being aware it should be updated itself (manually) with a version update, so we should keep that idea!
