### ISSUE TITLE
Beast apps won't launch on Windows 10

### ISSUE THREAD

**Issue by pvpoli** [CompEvol/beast2#829]
Hi,
I’m trying to run Beast in a Windows 10, but the application won’t open. When I double-click the icon, it bonce for a little while and nothing happens. It’s actually a very similar problem as the one described by Rene Malenfant in issue #771 (https://github.com/CompEvol/beast2/issues/771). Since de proposed solution for that issue doesn’t seem to solve my particular problem and since I’m working in a different OS, I thought it best to open a different issue.  

I have Java 8 installed, as seen in the output of java –version:
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

I’ve already tried uninstalling java, rebooting, reinstalling java, rebooting, but nothing has changed. For information, java is not shown as an active process on Windows Task Manager. Any ideas about what could be the solution for this issue?
Thanks!

**Comment by rbouckaert** [comment]
You installed the JDK, not the JRE, is that correct?

Have you tried to use a version of BEAST with java included?

**Comment by pvpoli** [comment]
Excuse me for the lack of details. Yes, I have the JDK installed, download from
https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

I tried both versions of BEAST (with and without java), but none seems to work.

Thanks for your answer.

**Comment by pvpoli** [comment]
I was able to load all applications by command prompt. Below an exemple for BEAUTi :
java -cp path/to/beast/lib/beast.jar beast.app.beauti.Beauti

I can't open the apps by double clicking the .exe icons... 

For my needs, the problem is solved, even though the original issue is not yet solved. Would you rather keep it as unresolved or to close the issue?

**Comment by rbouckaert** [comment]
Since you are probably not the only one with this issue, I'd rather keep this open. I would appreciate it if you could help doing a few more tests to find out what is causing this issue.

Can you start BEAUti from the command prompt using`\path\to\beast\beauti.exe` instead of the java command?

Are you using any virus software?

By the way, to load packages starting java directly, with java 8 you will need the `beast.load.jars` directive, like so:

`java -Dbeast.load.jars=true -cp path/to/beast/lib/beast.jar beast.app.beauti.Beauti`

**Comment by julievakulenko94** [comment]
Hi,
I faced the same problem with launching BEAST, and the solution of **pvpoli** worked for me.
When I start BEAUTi from command prompt using \path\to\beast\beauti.exe nothing happens, regardless of the presence or absence of special symbols.  

I tried launching with \path\to\beast\ located in C: and another drive, however, the result is the same.

I am using Dr.Web. software.

Thanks!

**Comment by rbouckaert** [comment]
@julievakulenko94  Thanks for that information!

I suspect the reason is the two-stage launch of all BEAST applications, which allows setting up the class path so that BEAST apps work with java 9 and up. The launchers may start (DensiTree -- which uses a different way to start -- does not seem to suffer from this problem), but the launcher is perhaps not allowed to kick off another process, so it seems nothing happens.

A possible solution is to create a release with java 8 bundled and using the way to launch applications as in BEAST v2.4. I created a release for windows that you can download [here](https://github.com/CompEvol/beast2/releases/download/v2.5.2/BEAST_with_JRE2.v2.5.2.zip) and is marked as v2.5.2 pre-release. If you could test this on your computer and let me know whether it launches that would great.

**Comment by julievakulenko94** [comment]
@rbouckaert, thank you so much! This release works perfectly!

**Comment by rbouckaert** [comment]
@julievakulenko94 thanks for testing and glad to see it works!

**Comment by rbouckaert** [comment]
The release script was updated for the windows version to use the v2.4 style launching, which appears to fix this issue.

**Comment by ymilesz** [comment]
I am also having this issue, and I have the latest version of BEAST2, it was working until I updated it.

**Comment by rbouckaert** [comment]
@ymilesz Do you have the version with the JRE included or the one without? If the latter, what version of Java are you running?

**Comment by ymilesz** [comment]
I have the version with JRE included.

**Comment by rbouckaert** [comment]
Possibly, it is because the version of java included in the BEAST release is not compatible with the version of Windows. If so, it is best to download and install java separately, for example from https://adoptopenjdk.net/, and install the version of BEAST that does not include java. If all is well, BEAST apps should start. 

If not, check that Java works by opening a command prompt (cmd from start menu) and type `java -version` then the `enter` key. If java is properly installed, it should show the version number, e.g., like so:

    java version "1.8.0_73"
    Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
    Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

Let me know if that works. Cheers, Remcp

**Comment by ymilesz** [comment]
Downloading the version without java worked, thank you!

**Comment by pkviatko** [comment]
I have the same issue with BEAST.v2.6.0.Windows without JRE included on Windows 10.
I have installed OpenJDK 11 from https://adoptopenjdk.net/ and running `java -version` shows:  
```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
```  

Yet, when trying to run BEAST I get:

> This application requires a Java Runtime Environment 1.6.0.  

So, somehow the instructions above doesn't work for me.

**Comment by rbouckaert** [comment]
@pkviatko thanks for the error message -- it is a bit puzzling though, since BEAST will not run with JRE 1.6.0, but requires at least version 8.

Have you tried the version with Java included?

**Comment by pkviatko** [comment]
@rbouckaert Thanks for the suggestion, it worked quite well for BEAST, but since other apps (e.g. Tracer, FigTree) do not have java included, they did not work.

After fiddling with different versions of OpenJDK I found that it only works with version 8, but not higher, and only if you check "Java Soft (Oracle) registry keys" during installation.

**Comment by rbouckaert** [comment]
@pkviatko Thanks for the information, and the tip for running with java from Oracle!

The version of BEAST with Java included should work for all applications, not only BEAST -- each application uses the same mechanism to discover which version of java to run. If BEAST runs but other applications (BEAUti, TreeAnnotator, etc.) do not, there is something peculiar going on, which makes things even more puzzling.

**Comment by ymilesz** [comment]
> Downloading the version without java worked, thank you!

Hello again, I tried updating to the latest version (2.6.3) and now the same problem of not launching is back. I've tried download Java OpenJDK 15 with the Java-less version and it didn't work. 

When I tried to double click the exe a pop up saying I need to install Java, so I tried that version (8, update 271) as well and now no pop ups but it still won't launch.

Thanks,

Miles

**Comment by sun-jiao** [comment]
> @pkviatko Thanks for the information, and the tip for running with java from Oracle!
> 
> The version of BEAST with Java included should work for all applications, not only BEAST -- each application uses the same mechanism to discover which version of java to run. If BEAST runs but other applications (BEAUti, TreeAnnotator, etc.) do not, there is something peculiar going on, which makes things even more puzzling.

For me, DensiTree works fine, but others won't launch.

**Comment by rbouckaert** [comment]
@sun-jiao Since you mention having java already installed, did you try the version of BEAST with JRE included? Sometimes, the release with JRE included will start, even though a java version 8 is already available.

**Comment by sun-jiao** [comment]
> @sun-jiao Since you mention having java already installed, did you try the version of BEAST with JRE included? Sometimes, the release with JRE included will start, even though a java version 8 is already available.

I've tried v2.6.5~2.6.7 with and without JRE, 6 versions in total, and none of them worked.
I finished my work using `java -cp`
