### ISSUE TITLE
Help writing a shell script to always fetch latest release .tgz?

### ISSUE THREAD

**Issue by Firedrops** [CompEvol/beast2#861]
I am trying to automate installation of beast in docker containers. For beast1, with some help from other githubbers, the following command works in downloading the latest release .tgz
```
curl -s "https://api.github.com/repos/beast-dev/beast-mcmc/releases/latest" | jq --arg PLATFORM_ARCH "tgz" -r '.assets[] | select(.name | endswith($PLATFORM_ARCH)).browser_download_url' | xargs curl -L -o /beast1.tgz
```
It was achieved as there is a single discriminator is at the end, thus `endswith` works.
However, for beast2, there is a further discriminator in the middle, e.g. `...v2.5.2...` vs `..._with_JRE.v2.5.2...`. I'm not sure how this can be filtered to always take the version without `_with_JRE`.

Could anyone please help with adapting the above command for beast2's naming structure?

**Comment by rbouckaert** [comment]
Perhaps this will do:

    curl -s "https://api.github.com/repos/CompEvol/beast2/releases/latest" | grep download | grep tgz | head -n 1 | awk '{print $2}' | xargs curl -L -o /beast2.tgz

broken down as

    curl -s "https://api.github.com/repos/CompEvol/beast2/releases/latest"

Download the contents of `/latest`

    | grep download 

list all entries that can be downloaded

    | grep tgz 

find all Linux releases, since these end in '.tgz'

    | head -n 1 

only take the first one -- there may be two: one with and one without JRE. If you want the one with JRE included, perhaps change to `grep JRE` instead.

    | awk '{print $2}' 

only take the file name

    | xargs curl -L -o /beast2.tgz

download into beast2.tgz

**Comment by Firedrops** [comment]
Beautifully written and explained. Thank you!
