### ISSUE TITLE
Optimising multi-species coalescent analysis in slurm

### ISSUE THREAD

**Issue by deoliveira86** [CompEvol/beast2#874]
Dear all,

I'm trying to run a multi-species coalescent analysis using 135 ultra-conserved loci present in 44 different bacteria, totaling in the end 136 partitions (i.e. 135 loci + 1 species tree). I tried to run three independent runs at my workstation, but for my calculations that would take ~2 months from the sampling to be finished, and after one month due the low ESS I just killed the processes. I reckon I need many more generations and time to reach convergence. The optimal solution would be to use the high performance cluster at my University and parallelise the run. The available resources are below:
            
basic     16-8   (CPUs/Nodes)
basic     16-38 (CPUs/Nodes)

My question is about the optimisation of the process using beagle, threads and instances parameters present in beast2 via a slurm batch. Does anyone have experience with that? I am suffering a bit to set up the run properly.

**Comment by rbouckaert** [comment]
In general it is hard to say what is the best configuration. You might want to have a look at how the CPU usage and especially the amount of time per million samples (as reported on screen output) varies by running BEAST with different number of threads for small chain lengths, and base your decision on that.

Have you considered the [StarBeast2](https://github.com/genomescale/starbeast2/) model (tutorial [here](https://taming-the-beast.org/tutorials/starbeast2-tutorial/)), which can converge much faster than *BEAST?

By the way, this facility is meant for developers and reporting bugs -- the BEAST user list (https://groups.google.com/forum/#!forum/beast-users) is more appropriate for this kind of questions.

**Comment by deoliveira86** [comment]
> Have you considered the StarBeast2 model (tutorial here), which can converge much faster than *BEAST?

Oh how nice, I will look into it right now. Thanks for the help and for the tutorial (sorry about posting this on the "bug" report github).

Best,
André

**Comment by rbouckaert** [comment]
Be aware that StarBeast2 does not benefit from threading much, but you can of course run multiple chains in parallel and use LogCombiner (one of utilities that come with BEAST) can be used to combine the logs in a single log.

**Comment by deoliveira86** [comment]
Hello,

Yes, I realised that today. It did not make such a huge difference invoking the beast with 1 or 4 threads. However, it did make a difference using -beagle and -beagle_SSE parameters.

> Be aware that StarBeast2 does not benefit from threading much, but you can of course run multiple chains in parallel and use LogCombiner (one of utilities that come with BEAST) can be used to combine the logs in a single log.

Yes, that sounds an excellent idea. Is there any drawback of running, for example, 40 chains in parallel instead of running only a single (really long) one in terms of the tree space investigated? I'm assuming if the chains run long enough the combination of multiple individual sampling results can be more beneficial than a single one. I think adjusting the sample frequency to a higher values (e.g. 10.000) can also benefit me during the combination of the results in the end and the size of the individual tree files generated throughout the mcmc chain.

**Comment by alexeid** [comment]
The cost of parallel chains in burnin. Each chain has to independently go through burnin. But that is the price you have to pay :) If you start them all from the same starting state then they are not actually independent and you can’t trust estimates of effective sample size based on between chain variance. So although it might increase burnin, it is better to start every chain from an independent random starting point, since then you can really trust the between chain variance estimates of effective population size.

**Comment by J-Moravec** [comment]
To expand on what Alexei said:

The useful sought-for property of MCMC is that when it samples the parameter space, then for large n the frequency of visited states is equal to their (posterior) probability. However, this applies only after the chain reached its stationary distribution. If you start in some random highly-unlikely space, it states will be definitely overrepresented in your samples compared to their normal probability. The standard procedure is to cut off these states, so-called burnin.

The problem is that while it is mathematically guaranteed that the MCMC will reach the stationary state, it is not guaranteed when. So in a complex problem, the MCMC chain can stay ages in the "wrong" part of the space. So longer chains are better, but then you have a problem with parallelization.

It is also generally better to run multiple chains just to check if they converged. Some other software, like MrBayes, does this by default.

**Comment by deoliveira86** [comment]
Thanks for all the input. I think the best approach will be to parallelise the runs with not so many generations, but still allow the MCMC chains to run long enough in order to visit as many states as possible. I can check in the end if they converged using tracer.

> it is better to start every chain from an independent random starting point, since then you can really trust the between chain variance estimates of effective population size.

If I send many parallel jobs the random numbers used to generate the starting tree will be always different? In other words, different executions of beast with the same .xml file always have different starting trees? Or this is something that I need to explicitly tell to the beast via the command line -seed?

**Comment by alexeid** [comment]
When you run a script to execute BEAST many times in quick succession, it can be that some of the runs are given the same seed, since, by default, the seed is taken as the computer’s clock time in milliseconds. So you either need to have a little pause in your execution script between successive executions (1 second is more than enough) or directly provide unique seeds (consecutive numbers starting from your favourite number is fine).

**Comment by deoliveira86** [comment]
Hello Alexei and Jiri,

Thanks for the input. Extremely helpful. I will send tomorrow the jobs to the slurm grid. Everything is set now. I am closing this issue and I will be sure that my future question will be addressed at the right place (https://groups.google.com/forum/#!forum/beast-users). 

Best,
André
