### ISSUE TITLE
Possible for full 2.6.1 release or build/make/compile from git clone?

### ISSUE THREAD

**Issue by Firedrops** [CompEvol/beast2#875]
Hi, I'm maintaining a docker that gets beast2 by `curl` and `wget`-ing the latest `release` through github api. I used to filter it down to ".Linux.tgz" for the right version.

However, with the 2.6.1 release, that is no longer possible, and the docker no longer builds.

I understand the justification for keeping it 2.6.1 an upgrade-only release through the UI, so if a full release is not planned, I wish to build/make/compile it within the docker via the `git clone` method. Is this currently supported? If so, what are the right steps?

**Comment by rbouckaert** [comment]
Would it be suitable to get the v2.6.0 release the way you currently do, then run `/path/to/beast/bin/packagemanager` (where `/path/to/beast` the path where you have BEAST installed) to install v2.6.1?

The steps that the packagemanager goes through are:

* get the BEAST package file (you can still use curl/wget for that) from https://github.com/CompEvol/beast2/releases/download/v2.6.1/BEAST.package.v2.6.1.zip.
* unzip the file in the package directory (defaults to `~/.beast/2.6/` on Linux), so you can unzip into ~/.beast/2.6/BEAST in order to install v2.6.1.

So, perhaps you can install v2.6.0 as per usual, then use the above two steps to upgrade to v2.6.1.

**Comment by Firedrops** [comment]
Thank you for the comments. The problem is that I still couldn't figure out how to automatically fetch the 'full release version' (I doubt this is very hard, I'm just very new to coding, this is another valid way of solving the issue I'm facing). The files tagged by github's `latest` no longer contain the full `...2.6.0.tar.gz`.

For the time being, I am using a static link to `wget` the full `...2.6.0.tar.gz`, and upgrading is simple enough. However, I think I will need to come back and revise the code when beast2 has the next full release, e.g. 2.7.0, or my docker will become outdated.

**Comment by boegel** [comment]
@rbouckaert Is there a way to update to Beast 2.6.1 without using `~/.beast`?

I'm installing Beast to a system-wide location, and would like to update that installation to 2.6.1 in one way or another (without letting each individual user run `packagemanager -update`, if possible).

Would running `packagemanager -add BEAST -version 2.6.1 -dir /path/to/beast` to that?
And if so, would `beast -version` print 2.6.1 (or still 2.6.0)?
How can I verify whether Beast 2.6.1 is the version I'm using?

**Comment by rbouckaert** [comment]
@boegel  BEAST looks in user package directories, but also in a system package directory. If the `beast.system.package.dir` environment variable is specified, that is where it looks, but by default the system directory is 

 `\Program Files\BEAST\2.6` for Windows
 `/Library/Application Support/BEAST/2.6` for OS X
 `/usr/local/share/beast/2.6` for Linux

so if that is where you install the BEAST 2.6 package by hand, or via the `-dir` option to the package manager, it should be system wide available.


`beast -version` should print `v2.6.1` if v2.6.1 is installed as a package, even if the launcher is from v2.6.0.

**Comment by FokkeDijkstra** [comment]
This doesn't work. When I run the command @boegel and @rbouckaert suggest it adds a folder ```archive/BEAST/2.6.1``` to the directory specified with -dir. 
When running ```beast -version``` it still says it is version 2.6.0. 
```beauti``` wants to update to version 2.6.1, but it does this in ```$HOME/.beast```. When run after this update beast does recognize version 2.6.1.

I also tried unzipping https://github.com/CompEvol/beast2/releases/download/v2.6.1/BEAST.package.v2.6.1.zip in the installation directory. This does update BEAST to version 2.6.1. 

**But**, since beast (for whatever reason) copies its files to ```$HOME/.beast```, when the user has been running 2.6.0, the user will still have 2.6.0, even though the 2.6.1 installation is added to his/her path.
It took my a few hours to figure this out, while I was trying to update the centrally installed BEAST 2.6.0 to 2.6.1.

Questions:

1. Why does BEAST cache its libraries in the users home directory? This may cause them to inadvertently run an older version.
1. Why does the ```packagemanager -dir``` option not work like it should?
1. Why is there no full release of the updated version, which would have prevented this issue multiple people run into?

**Comment by rbouckaert** [comment]
@FokkeDijkstra  BEAST looks in a number of places for packages:

* the user directory `$HOME/.beast` on Linux
* the system directory `/usr/local/share/beast/` on Linux
* path specified in the `BEAST_PACKAGE_PATH` environment variable
* (path specified in `beast.install.dir` directive -- intended for package developers)

So, probably the easiest way to upgrade a centrally installed version is to put it in the system directory, assuming it is available through a shared file system.

Libraries are cached for speed of loading BEAST, BEAUti, and other applications -- discovering packages can take quite a bit of time when many packages are installed. A crude way to force BEAST to discover packages on every start-up is by making the file `~/.beast/2.6/beauti.properties` empty and read-only (this works, but causes errors to be thrown), or make it a symbolic link that contains libraries in `/usr/local/share/beast`.

A full release require much more testing (3 OSs and with/without JRE), so for relatively small updates that did not seem to be worth the bother. However, given your use case, this is something to rethink.

**Comment by rbouckaert** [comment]
There is now a fully built v2.6.2 release and a v2.6.3 release imminent, so I think this issue can be closed.
