### ISSUE TITLE
Help with GUI dockerfile

### ISSUE THREAD

**Issue by Firedrops** [CompEvol/beast2#878]
I am trying to add the GUI functionality from beast2's dockerfile as part of a larger one I am creating. I am doing this by copying the code in beast2's dockerfile to the end of mine. My dockers are based on others which are based on `debian stretch`, which should be the same as beast2's `openjdk:8`

However, I am confused about the `ADD . ./` function. I believe this serves to copy files in the beast2's git clone-d folder into the docker's root directory `/`, so I initially tried without this. When the build failed complaining about missing `build.xml`, I added `ADD build.xml ./` and copied beast2's `build.xml` file to my git folder. This bypasses the issue but now it's complaining:
```
xauth:  file /root/.Xauthority does not exist

New 'X' desktop is dee7885834c9:0

Creating default startup script /root/.vnc/xstartup
Starting applications specified in /root/.vnc/xstartup
Log file is /root/.vnc/dee7885834c9:0.log

Buildfile: /build.xml

BUILD FAILED
/build.xml:721: taskdef class com.oracle.appbundler.AppBundlerTask cannot be found
 using the classloader AntClassLoader[]
```
I thought this `./Xauthority` is something that vnc generates, and I also cannot locate it in beast2's git repository, so I don't see how `ADD . ./` would've solved this.

Is anyone here familiar with the code enough to help with this troubleshooting? Full docker code [here](https://github.com/Firedrops/qimr_mtb/blob/master/rebase/Dockerfile), at line 285. `ant` and other dependency packages were installed way up at line 52. I also have otherwise installed beast2 on line 182, so if the Dockerfile also builds beast2, there might be redundancy issues? (not a priority issue currently)

**Comment by tgvaughan** [comment]
It doesn't look like the xauth message is the problem (that's merely a warning and probably occurs in the testing docker image build too).  The real problem is the class not found error at the end.  It sounds to me like a JDK version problem.

**Comment by Firedrops** [comment]
`java -version` returns
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1~deb9u1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```
is this an issue?

**Comment by tgvaughan** [comment]
Ok, I jumped to a wrong conclusion.  The real problem is, as I said, the class not found error.  However it has nothing to do with an incorrect java version, and everything to do with your replacement of `ADD . ./` with `ADD build.xml ./`.  The former adds everything, the latter only adds build.xml.  The error you're seeing is a result of ant not being able to find the required class files (which your ADD omits).

Replacing the old ADD line and the original CMD line causes your dockerfile to build and run without a problem, at least on a macbook.  TBH though I commented out lines 53->283 in your file when testing, so it's possible that something in that chunk is causing you problems.

**Comment by Firedrops** [comment]
Thank you for the further troubleshooting! So as mentioned above, I should already have the full beast2 git in `/beast2`, so I thought this may be issues with hardcoded paths, so I moved it with `mv /beast2 /root/beast2` to match the pathing style of the rest of the `Dockerfile`. Then I `cd /root/beast2` to mimic `WORKDIR /root/beast2` and tried `vncserver $DISPLAY -geometry 1920x1080; ant travis` again. 
This is what I'm seeing now:
```
New 'X' desktop is d13eac4139af:0

Starting applications specified in /root/.vnc/xstartup
Log file is /root/.vnc/d13eac4139af:0.log

Buildfile: /root/beast2/build.xml

BUILD FAILED
/root/beast2/build.xml:721: taskdef class com.oracle.appbundler.AppBundlerTask cannot be found
 using the classloader AntClassLoader[]

Total time: 0 seconds
```
Does that mean the creation of the vncserver is complete, or is the `AntClassLoader` error still blocking vnc from functioning?

**Comment by tgvaughan** [comment]
At this point I would just comment out the CMD and run `docker run -it IMAGE /bin/bash` where IMAGE is the name of the docker image you've built.  The result should be a shell with your working directory containing both build.xml and the rest of the BEAST 2 source and libraries.  In particular, the directory ./lib/bundler should contain `appbundler-1.0.jar`.  The directory name of the current directory should also be "beast2".  If any of these things are not true, this is where the problem is.

**Comment by tgvaughan** [comment]
And I guarantee it has nothing to do with VNC.

**Comment by Firedrops** [comment]
I have realised that the `;ant travis` part and `build.xml` are for building beast2. Since they were added to my docker previously via the git clone method, these steps can be omitted. 

I am running my docker with `sudo docker run -it -p 5900:5900 13a /bin/bash` where `13a` is the image's id. Once I'm in, I start vnc with `vncserver $DISPLAY -geometry 1920x1080`. However, I am unable to connect to `localhost:5900`. 

Could it have anything to do with the fact that the docker is being run within am Ubuntu VM on Oracle Virtualbox? I am also attempting the VNC connection from within the VM.
