### ISSUE TITLE
BeastMCMC thread pool is not used at all?

### ISSUE THREAD

**Issue by focusjava** [CompEvol/beast2#889]
src/beast/app/BeastMCMC.java：run() // line 355
```
public void run() throws Exception {
        g_exec = Executors.newFixedThreadPool(m_nThreads);
        m_runnable.run();
        g_exec.shutdown();
        g_exec.shutdownNow();
    } // run
```
The thread pool is not called, and only one CPU is used to observe the CPU utilization by running the program.
-----------------------------------------------
The test code is as follows:
```
	public static void main(String[] args) {
		int threadCount = 6;
		long seed = beast.util.Randomizer.getSeed();
		File inputFile = new File("./examples/testBSP.xml");
		
		final List<String> MCMCargs = new ArrayList<>();
		MCMCargs.add("-overwrite");
		MCMCargs.add("-threads");
		MCMCargs.add(threadCount + "");
		MCMCargs.add("-seed");
		MCMCargs.add(seed + "");
//		MCMCargs.add("random");
		MCMCargs.add(inputFile.getAbsolutePath());

		try {
			final BeastMCMC beastMCMC = new BeastMCMC();
			beastMCMC.parseArgs(MCMCargs.toArray(new String[0]));
			beastMCMC.run();
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
```

I hope to receive your reply as soon as possible. Thanks

**Comment by rbouckaert** [comment]
Starting BEAST with the `-threads` option will create space in the thread pool.

The thread pool is used during the MCMC by some objects, but not all. For example, `ThreadedTreeLikelihood` will use threads by default, and `CompoundDistribution` will use threads only if the `useThreads` input is set to `true`. 

Even then it is  possible that you won't see any CPU usage above 100% because the benefit of doing calculations in parallel may be canceled out by the overhead of threading.

Hope this clarifies things.

**Comment by focusjava** [comment]
Thank you very much for your reply. Wish you a happy life and smooth work!
