### ISSUE TITLE
"Two sequences with different length found" error when importing STR CSV as multi-partition

### ISSUE THREAD

**Issue by santiagosnchez** [CompEvol/beast2#899]
Dear Remco,

I'm trying to import a CVS STR file into BEAUTi (v2.6.2) with the aim of performing an EBSP analysis. But when I specify the file as multi-partition BEAUti returns an error saying:

**Loading of X.csv file failed: Two sequences of different length found: 2 != 1**

I checked my CSV file and this only happens for loci that have different order magnitude differences in alleles. For example 1 and 12 repeats. This does not happen for loci with alleles in the same order of magnitude: 1 and 5 repeats. I'm assuming BEAUTi is interpreting 1 and 12 as aligned characters and therefore `len(allele1) == 1 and len(allele2) == 2`

I was able to trace this to these set of lines in the main BEAST2 code:
https://github.com/CompEvol/beast2/blob/486f8e442d3c7f3dcde1fdc13131377b973bbfea/src/beast/evolution/alignment/Alignment.java#L331-L332

And the conflict with BEASTvntr seems to be happening somewhere here:
https://github.com/rbouckaert/BEASTvntr/blob/fee0c32c1cbdde39253a07a587c6e451907b0804/src/beast/app/fileimporters/CSVImporter.java#L209-L214

It looks like this be a simple bug to fix.

Thanks!

**Comment by rbouckaert** [comment]
Turns out there are other data types that do not have constant code lengths, like the [`FiniteIntegerData`](https://github.com/arjun-1/BEASTvntr/blob/master/src/beast/evolution/datatype/FiniteIntegerData.java) in the VNTR package.

Adding a method to `DataType` so that the class can indicate whether the code length is constant or not could solve this problem, e.g., something like so:


```
	default public boolean hasConstantCodeLength() {
		return true;
	}
```
and have `UserDataType`, `StandardData` and `FiniteIntegerData` override this by returning false.
