### ISSUE TITLE
LogCombiner: throws `NullPointerException` when output `-o` is not defined.

### ISSUE THREAD

**Issue by J-Moravec** [CompEvol/beast2#962]
According to the `-help`, LogCombiner should print to stdout. However, it throws `NullPointerException` when `-o` is not specified:

```
java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:276)
	at beast.app.tools.LogCombiner.combineLogs(Unknown Source)
	at beast.app.tools.LogCombiner.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at beast.app.beastapp.BeastLauncher.run(Unknown Source)
	at beast.app.tools.LogCombinerLauncher.main(Unknown Source)

```

This seems to be caused by:
* `combineLogs` expect `m_sFileOut` to be a String to a file
* `LogCombiner` constructor or `parseArgs` do not initialize `m_sFileOut`
* The check (and only warning) that the `m_sFileOut` is `NULL` is only in the UI part, not in the command line part.

The easiest fix seems to be to correct the `-help` info and either initialize `-o` to `output.log` (as suggested by `-help`) or add a check/put `-o` into required parameters.

Reading Java documentation, I wasn't able to find if `java.io.File` supports stdout, i.e., through a `""` string. So to make behaviour consistent with documentation would potentially require larger changes.

Additionally, seems that `m_sFileOut` is opened both in `parseArgs` and `combineLogs` as `m_out`. Although with a slightly different class handle.

**Comment by tgvaughan** [comment]
Hi @J-Moravec, thanks for spotting this!  Actually the error is just in `combineLogs()` on line [239](https://github.com/CompEvol/beast2/blob/c887ec19ceb9c80cd4ccb4a197c5be537f2fd4cc/src/beast/app/tools/LogCombiner.java#L239) and the following try-catch block.  Both assume that (a) `m_sFileOut` is non-null, and that (b) the file hasn't been opened.  (As you point out, this has already been done during the command line argument parsing.)

The fix is just to remove the try-catch block, and to fix the logging line above it.  Then the programme behaves as described in the usage text.  (This is more versatile than choosing a default file, as it allows people to pipe the output of LogCombiner through something else.)

**Comment by J-Moravec** [comment]
My bad, totally missed https://github.com/CompEvol/beast2/blob/c887ec19ceb9c80cd4ccb4a197c5be537f2fd4cc/src/beast/app/tools/LogCombiner.java#L31.
